### ISSUE TITLE
Tracking Class Diagram Conventions

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#123]
This issue is opened for tracking the writing conventions for each class diagram. Every member is expected to write their class diagrams according to conventions decided on the [meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%239-09.04.2022) in 09.04.2022. (Check Class Diagrams section in the meeting notes.)
- [ ] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [ ] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [ ] Muhammet Şen
- [ ] Bengisu Takkin
- [ ] Burak Yılmaz
- [ ] Salim Kemal Tirit
- [ ] Mertcan Özkan

Deadline: 11.04.2022, 21.00

**Comment by mertcan-ozkan** [comment]
every one has updated their class diagram based on the conventions.
