### ISSUE TITLE
Documenting Task List for RAM and Tracking Completition Progress

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#134]
### Task: 
For the upcoming Milestone 1 Report (other tasks are mentioned in #132), a RAM (responsibility assignment matrix) needs to be prepared and filled out. After I enter the tasks into the Google Sheets document @nurlandadashov02 has prepared, team members will fill out the matrix for their corresponding columns. 

**Main Categories:**
- Infrastructure Setup
- Requirements
- Scenarios & Mockups
- Class Diagrams
- Use Case Diagrams
- Sequence Diagrams
- Meetings
- Research
- Milestone 1 Report
- Determining Teams

### Required tools (if applicable) or researches:
Google Sheets
### Place to put the documentation:
Milestone 1 Report (after its upload, I will link corresponding document)

### Deadline: 14.04.2022 12.00

**Comment by hsuleerkul** [comment]
People who filled in the RAM for their columns : 

- [ ] Ahmet Kudu
- [ ] Arif Akbaba
- [ ] Bengisu Takkin
- [ ] Bilal Aytekin
- [ ] Burak Yılmaz
- [ ] Hatice Şule Erkul
- [ ] Kadir Ersoy
- [ ] Mehmet Gökberk Arslan
- [ ] Mertcan Özkan
- [ ] Muhammet Şen
- [ ] Nurlan Dadashov
- [ ] Salim Kemal Tirit

**Deadline to fill in the matrix:** 14.04.2022 20.00

**Comment by hsuleerkul** [comment]
The RAM is completed and reviewed. You can see the RAM in this pdf file. [RAM.pdf](https://github.com/bounswe/bounswe2022group3/files/8496748/RAM.pdf). Congrats everyone!
