### ISSUE TITLE
Collecting Personal Efforts for Milestone 1 Report

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#146]
### Task
All team members need to collect their personal efforts so far for the Milestone 1 Report. These will be collected here as comments. Then I will move them to the Milestone 1 Report and hand it over to our communicator @yilmaz-burak for submission to Moodle. The reason why we do this here is essentially to document our communication.

- [x] Arif Akbaba
- [x] Mehmet Gökberk Aslan
- [x] Bilal Aytekin
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Salim Kemal Tirit
- [x] Burak Yılmaz

### Place to Put the Documentation
Milestone 1 Report.
### Deadline
April 15, 20:00.

**Comment by ersoykadir** [comment]
Created a personal Wiki page.
Done research on different GitHub repositories.
Studied Git.
Tracked personal wiki pages. [#2]
Reviewed [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) glossary. [#15]
Reviewed previous groups' requirements pages.
Wrote the requirements for Event Organization. [#25]
Documented [Meeting notes 3](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%233-13.03.2022). [#28]
Gathered questions about the Requirements. [#26] 
Wrote User [Scenario 1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1). [#37,#53]
Documented [Customer meeting 1](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Meeting-Notes-%231-23.03.2022). [#58]
Documented [Meeting Notes 6](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022). [#65]
Designed Use Case Diagram for `Register`. [#79]
Designed Use Case Diagram for `Create Profile`. [#89]
Designed Class Diagram for `User` class. [#100]
Designed Class Diagram for `UserService` class. [#104]
Designed Sequence Diagram for `Register/Sign-up`. [#107]
Updated Acceptance Criteria part of [Scenario 1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1#acceptance-criteria). [#103]
Handled Class Diagram relations. [#126]
Designed Use Case Diagram `Follow/Block User`. [#127]
Documented Evaluation of Project Plan. [#138]
Contributed to RAM, Project Plan and to the future plan of the project.
Attended to all meetings.

**Comment by nurlandadashov02** [comment]
## Nurlan Dadashov
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Nurlan-Dadashov).
- Done research on different GitHub repositories, documented a [favourite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories#storybook).
- Studied Git.
- Reviewed [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) glossary. [#15]
- Wrote Non-functional Requirements. [#12]
- Reviewed the requirements written by other team members.
- Created a web mockup for User [Scenario 3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3). [#38]
- Documented [Meeting Notes 5](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%235-25.03.2022). [#57] 
- Revising Privacy requirements.  [#64]
- Designed Use Case Diagram for `Events`. [#68]
- Designed Class Diagram for `Event` class. [#69]
- Designed Sequence Diagram for `Event Creation`. [#109]
- Revised Event requirements.
- Documented Evaluation of Communication Plan. [#138]
- Contributed to RAM, Project Plan, and to the future plan of the project.
- Attended all team meetings.

**Comment by mertcan-ozkan** [comment]
## Mertcan Özkan
- Created [personal wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Mertcan-%C3%96zkan)
- Created and customized labels for issues[#7 ]
- Done research on different git repos and choose a [favouirte one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories).
- Studied Git.
- Created the system  requirements profile page.[#24 ]
- Edited system  requirements-profile page ,with all of its subsections , multiple times based on feedback.[#51 #31 #130  ]
- Created [user scenerio 1]() with kadir. [#37 ]
- Reviewed user scenerio 1 mockups.[] 
- Crated use case edit view profile page. [#80 ]
- Reviewed create profile use case written by [Kadir](#89 ), then merged it with use case edit view  use case.
- Created class diagram personal information.[#92  ]
- Created sequence diagram - edit profile page [#120 ].
- Written evaluation of requirements for milestone 1 report. [#137]
- Tracked editing the acceptance criteria of scenerios after requirement changes. [#103 ]
- Tracked class diagram writing conventions. [#123 ]
- Participated in all group and customer meetings.
- Created my part of individual work in milestone 1 report.
- Helped in creating the project plan and talked about future plans.
- Created weekly effort page for all weeks.

**Comment by Goko6** [comment]
# Mehmet Gökberk Arslan
- Created a personal [wiki page]( https://github.com/bounswe/bounswe2022group3/wiki/Mehmet-G%C3%B6kberk-Arslan) [#2]
- Did repository research [#5]
- Studied git and prepared a wiki page for it [#9]
- Wrote the requirements for recommendations [#16]
- Created the mobile mockup for [scenario#2]( https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) creating a discussion [#46], [#50]
- Created the [use case diagram]( https://github.com/bounswe/bounswe2022group3/wiki/Use-Case-Diagrams) for enrolling a course and assisting on the use case diagram for viewing course content [#87], [#71]
- Created the [class diagram]( https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams) for comment class [#85]
- Created the [sequence diagram]( https://github.com/bounswe/bounswe2022group3/wiki/Sequence-Diagrams) for enrolling a course [#116]
- Joined all the group and customer meetings
- Documented my personal effort every week
- Wrote the evaluation of UML diagrams in the milestone report [#142]
- Filled in my part of the RAM [#134]

**Comment by Brunettow** [comment]
## Bengisu Takkin
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Bengisu-Takkin).
- Done research on different GitHub repositories, documented a [favourite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories#react).
- Studied Git.
- Wrote user requirements. [#18]
- Reviewed the requirements written by other team members.
- Documented [Meeting Notes 2](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%232-11.03.2022) [#19]
- Created a template for Main Page for Web [#35]
- Created a template for Course Page for Web [#36]
- Created Persona for [Scenario 3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3). [#45]
- Revised User Requirements with @salimtirit. [#60]
- Documented [Customer Meeting #2 Notes](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Meeting-Notes-%232-30.03.2022) [#61]
- Made drastic changes in the User Requirements according to the team revisions with @salimtirit and @muhammetssen. [#63]
- Created a Use Case Diagram for Create Content. [#75]
- Created a Class Diagram for Email Service. [#77]
- Tracked the revisions of the Use Case Diagram Relations. [#121]
- Tracked [Weekly Efforts #6](https://github.com/bounswe/bounswe2022group3/wiki/Week-6-Personal-Efforts) [#128]
- Created a Table for Deliverables with Their Statuses. [#144]
- Contributed to RAM, Project Plan, and to the future plan of the project.
- Attended all team meetings.

**Comment by bilalcim** [comment]
* Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Bilal-Aytekin).
* Created a personal effort page draft. #3 
* Searched for original GitHub repos, [reported](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories#vscode-lean4) the [**vscode-lean4**](https://github.com/leanprover/vscode-lean4).
* Watched the ["Git for Ages 4 and Up"](https://www.youtube.com/watch?v=1ffBJ4sVUb4&t=1s).
* Completed the "Infrastructure Setup" task on Moodle.
* Prepared the search engine requirements, revised according to the team and customer reviews. #13 
* Reviewed the requirements written by other team members in team meetings.
* Created the mobile mockup for [Scenario #3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3). #41 
* Detailed the [privacy section](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#33-privacy) of [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements). #54 
* Designing the use case diagram for searching functionality. #81
* Designed the class diagram for the `SearchService` class. #82 
* Designed a sequence diagram for searching. #105 
* Filled the responsibility assignment matrix.
* Collecting all the evaluations, diagrams and personal efforts reports and compiling them for the Milestone 1 Report to be submitted. #145 
* Documented my personal efforts weekly.
* Attended all the meetings, both team and customer.

**Comment by muhammetssen** [comment]
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Muhammet-%C5%9Een).
- Investiaged different repositories to understand how to use wiki and issue systems in an efficient way. Moreover, documented [my favorite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories#obs-studio)
- Documented [Meeting Notes #1 04.03.2022](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231--04.03.2022)
- Reviewed and tracked [#27] requirements. Added requirements prepared by other team members to [wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) as they get completed and reviewed.
- Created [Scenario 2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) #48
- Tracked [Weekly Efforts 4](https://github.com/bounswe/bounswe2022group3/wiki/Week-4-Personal-Efforts) #59
- Changed the design of the requirements page in order to increase readability. #76
- Designed the use case diagram for `Managing Notes` #78 
- Designed the class diagram for `Note` #84 
- Designed the class diagram for `Enrollment` #88 
- Designed the class diagram for `Feedback` #113 
- - Designed the class diagram for `UserService` #104 with @ersoykadir  
- Improved the intergration between `Enrollment` and `Badge` classes by collabrating with @hsuleerkul  #97 
- Documented [Meeting Notes #5 04.04.2022](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231--04.03.2022) #98
- Created sequence diagrams for Managing Notes #119 
- Tracked statuses of all sequence diagrams #131
- Prepared project plan

**Comment by hsuleerkul** [comment]
### Hatice Şule Erkul
- Created a [personal wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Hatice-%C5%9Eule-Erkul)
- Documented my favorite Github Repos [here](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories#outlookgooglecalendarsync) and [here](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories#steamvr-unreal-plugin)
- Edited Wiki [Home page](https://github.com/bounswe/bounswe2022group3/wiki) and the sidebar. #1 
- Wrote the [Glossary of the Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#glossary). #15
- Documented the [Answers of Questions about Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Questions-to-Customer) page. #30 
- Created a template for Mobile Mockups. #32 
- Wrote the Acceptance Criteria of [Scenario 2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) #44 
- Edited the [Glossary of the Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#glossary) to add new terms and update the ambiguities. #56 
- Prepared a use case diagram for View Course Content functionality #71 
- Prepared a [Class Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams) for Achievement class #72 (Later Removed)
- Revised the [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements), added Feedback functionality into it. #73 
- Discussed about overlapping features of Achievement and Enrollment classes with @muhammetssen. #97 
- Created the [Class Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams) for Badge Class. #99
- Created the  [Class Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams) for Feedback Class. #114  
- Prepared a [Sequence Diagram for Modifying Custom Badges](https://github.com/bounswe/bounswe2022group3/wiki/Sequence-Diagrams#modify-a-badge---hatice-%C5%9Eule-erkul) #101 
- Prepared Sequence Diagrams for [Viewing Course Content](https://github.com/bounswe/bounswe2022group3/wiki/Sequence-Diagrams) #129 
- Updated the Acceptance Criteria of [Scenario 2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) #103 
- Updated my Use Case Diagram's [issue](https://github.com/bounswe/bounswe2022group3/issues/71)'s description. #108
- Documented meeting notes of [Meeting #9](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%239-09.04.2022) #122 
- Tracked the task list for Milestone 1 Report. #132 
- Documented Task List for RAM and Tracked Completition Progress. #134 
- Wrote an evaluation of RAM. #136

**Comment by yilmaz-burak** [comment]
## Burak Yılmaz
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Burak-Y%C4%B1lmaz).
- Prepared communication channel #10.
- Done research on different GitHub repositories, documented a [favourite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories).
- Studied Git.
- Track weekly efforts - 2 #20
- Documenting System-Communication Channel Requirements #21 
- Documenting System-Annotation Requirements #22 
- Generated and commented questions about the Requirements. #26
- Created User Scenario 3 #42, #52
- Configure and distribute Lucid app #62 
- Designed Use Case Diagram for Create Poll #66 
- Designed Class Diagram for Poll class #67 
- Track weekly efforts - 5 #90 
- Updated Acceptance Criteria part of Scenario 3 #103 
- Designed Use Case diagram for Admin #106 
- Tracking the addition of requirements to use case scenarios #108 
- Created Sequence Diagram for Poll Actions #117 
- Created Sequence Diagram for Admin actions #118 
- Evaluated Project repository #143 
- Contributed to RAM, Project Plan.
- Attended to all the meetings.

**Comment by arfakbaba** [comment]
## Arif Akbaba
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Arif-Akbaba).
- Done research on different GitHub repositories, documented a [favourite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories).
- Studied Git.
- Research about Markdown 
- Created [favorite GitHub repositories page](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories)
- Tracked all team members fovorite repositories research. [#5]
- Reviewed the requirements written by other team members.
- Reviewed previous groups' requirements pages.
- Wrote the requirements for Note Taking. [#23]
- Design Mobile Mockup [Scenario 1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1#mobile-mockup). [#40]
- Adjusting Mobile Mockup [Scenario 1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1#mobile-mockup). [#49]
- Designed Use Case Diagram for Create Course. [#83]
- Designed Class Diagram for Course class. [#86]
- Designed Sequence Diagram for Create Course. [#112]
- Documented Executive summary for M1. [#140]
-  Filled the responsibility assignment matrix.
- Contributed to RAM, Project Plan and to the future plan of the project.
- Participated in all group and customer meetings.
- Created weekly effort page for all weeks.
-  Wrote my part of individual work in milestone 1 report.

**Comment by salimtirit** [comment]
## Salim Kemal Tirit
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Salim-Kemal-Tirit).
- Done research on different GitHub repositories, documented a [favorite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories).
- Studied Git.
- Watched the ["Git for Ages 4 and Up"](https://www.youtube.com/watch?v=1ffBJ4sVUb4&t=1s).
- Created [Communicaion Plan Page](https://github.com/bounswe/bounswe2022group3/wiki/Communication-Plan). (issue #6)
- Updated communication plan. #14
- Documenting User Requirements #17
- Reviewed the requirements written by other team members. 
- Created web mockup for user scenario # 1 #39 
- Revised User Requirements with @Brunettow #60 
- Changed the User part in the Requirements with @Brunettow #63
- Designed Use Case Diagram for Login / Sign in #91
- Designed Class Diagram for AuthorizationService class. (This class is deleted afterward.) #94 
- Designed Class Diagram for Chapter class. #111 
- Documented [Meeting Notes 8](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%238-05.04.2022). #115 
- Designed Sequence Diagram for Login / Sign in #124 
- Wrote an evaluation of the tools used #135 
- Contributed to RAM and Project Plan.
- Participated in all the meetings.
- Created a weekly effort page for all weeks.
- Wrote my part of individual work for the milestone 1 report.

**Comment by ahmetkudu** [comment]
## Kadir Ersoy
- Created a [personal Wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Ahmet-Kudu).
- Done research on different GitHub repositories, documented a [favourite one](https://github.com/bounswe/bounswe2022group3/wiki/Favorite-Repositories).
- Studied Git.
- Updated [readme file](https://github.com/bounswe/bounswe2022group3/issues/11)
- Reviewed previous groups' requirements pages.
- Designed web mock-up for the [scenario 2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2)
- Designed for the [issue template](https://github.com/bounswe/bounswe2022group3/wiki/Issue-Template)
- Added admin modulation to the requirements [#74](https://github.com/bounswe/bounswe2022group3/issues/74)
- Designed Use Case Diagram for `Discussion Forum`. [#93](https://github.com/bounswe/bounswe2022group3/issues/93)
- Designed Class Diagram for `Discussion Forum` class. [#95](https://github.com/bounswe/bounswe2022group3/issues/95)
- Designed Sequence Diagram for `Discussion Forum`. [#102](https://github.com/bounswe/bounswe2022group3/issues/102)
- Added comments to glossary and improving requirements [#110](https://github.com/bounswe/bounswe2022group3/issues/110)
- Written an Evaluation of Scenarios & Mockups [#139](https://github.com/bounswe/bounswe2022group3/issues/139)
- Contributed to RAM, Project Plan and to the future plan of the project.
- Attended to all meetings.

**Comment by hsuleerkul** [comment]
Thanks Eveyone !
