### ISSUE TITLE
Tracking Weekly effort of Week 9

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#155]
All the team members should report their weekly efforts on this [wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Week-9-Personal-Efforts) 

So far:
- [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Burak Yılmaz
- [x] Salim Kemal Tirit
- [ ] Mertcan Özkan

Deadline: 08.05.2022, 23:59
