### ISSUE TITLE
[Practice App]: Implementing quiz feature 

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#170]
## Task
As my functionality to practice app, I will use [Open Trivia DB API](https://opentdb.com/api_config.php) to implement our own quiz functionality. Users will be able to create quizzes from 24 categories on `Open Trivia DB` and save the quizzes to access later. I will extend the use of `Open Trivia DB`. It does not allow users to get questions from different categories at the same call and do not save the created quizzes for users. I am going to implement these two main properties using GET and POST methods of `Open Trivia DB API`

I have already created the branch I will work on and I have done research about JS. I have completed courses on NodeJS, ExpressJS and MongoDB and I am ready to code!

## Backend
**Required endpoints** : 
- Create a new quiz
- View user specific quizzes
- View available categories

## Frontend
**Views:**
- Main quiz page to choose an action
- Form for choosing quiz attributes
- List of saved quizzes
- List categories and question counts 

## Todo List
- [ ] Document the research done on JS
- [x] Implement GET for categories
- [x] Implement GET for saved quizzes
- [x] Implement POST for creating new quizzes
- [x] Prepare the DB with preliminary data (Category names and question counts)
- [x] Design a main quiz page
- [x] Design a quiz creation page
- [x] Design a category info page
- [x] Design a page for listing saved quizzes

**Deadline:** TBD

**Comment by muhammetssen** [comment]
Done!
