### ISSUE TITLE
[Practice App]: Implementing Email Verifier

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#175]
### Task
Implementing an API that verifies given email addresses. I will use [this](https://eva.pingutil.com) API that returns JSON object.
 
### Requirements
* User shall verify any email address..
* User shall save email addresses to the database.
* User shall view email addresses that previously saved.

### Views
1. One main view where the user can enter an email address
2. A button for submitting the email address.
3. A button for saving the email address.
4. A list view that shows previously saved email addresses.

### Endpoints
`verifyEmail` is a `POST` method which takes an email address as an input and returns whether the address is valid or not.
`saveEmail` is a `POST` method which takes an email address as an input and saves the email address to the database.
`getEmails` is a `GET` method which returns already saved email addresses.

## Todo List
- [x] Document the research done.
- [x] Dockerize the app.
- [x] Implement a GET request for listing emails.
- [x] Implement a POST request for saving emails.
- [x] Implement a POST request for verifying emails.
- [x] Prepare a table in DB.
- [x] Design the frontend page.
- [x] Write requirements for the practice app.
- [x] Design sequence diagram.
- [x] Design class diagram.
- [x] Design Use case diagram.
- [x] Document the work.
- [x] Do testing.

Deadline: 20.05.2022, 23.59

**Comment by Brunettow** [comment]
### Main page:
![image](https://user-images.githubusercontent.com/63921045/169292837-192a5cec-2bd0-46dc-8fea-2fab238275a5.png)

**Comment by muhammetssen** [comment]
Done!
