### ISSUE TITLE
[Practice App]: Implementing Lyrics Api

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#179]
## Task
For my part in the practice app, I will use [Genius Api](https://docs.genius.com/) to implement a lyrics searching and saving site. Searching with a keyword that is related to any song will be possible. The user will be directed to a site containing lyrics. The user will be able to save that site's URL if s/he wants to. 

I created the branch I will work on. I have been struggling to understand the base code of the project. I have watched many tutorials and read many documentations. I think I am ready to code finally.

## Backend
**Required endpoints** : 
- Search with a parameter.
- Save a quiz.

## Frontend
**Views:**
- Search page with a place to enter a parameter and a search button.
- List search results.
- List of saved pages.

## Todo List
- [ ] Document the research done.
- [x] Implement GET for search.
- [x] Implement GET for saved pages.
- [x] Implement POST for saving lyrics.
- [x] Prepare a table in DB.
- [x] Design a search page.
- [x] Design a saved lyrics page.
- [x] Document the work.
- [x] Do testing.

**Deadline:** TBD

**Comment by salimtirit** [comment]
- [ ] Post for saving lyrics need to include user data.
- [ ] Get saved pages should only bring the current users saved lyrics.

**Comment by salimtirit** [comment]
- [ ] Creade api documentation using swagger

**Comment by salimtirit** [comment]
All done
