### ISSUE TITLE
[Practice App]: Implementing Weather API

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2022group3#181]
## Task: 
I'll use an external API to implement a Weather API in my section of the Practice App. The AI engine's movements will be obtained via an external API. I'll look at Weather APIs and choose one. Then I'll go over the documentation and figure out which endpoints will be used in the Practice App.

## Todo List:
- [ ] Learn how to use Next.js for front-end and Express.js for back-end to stick to the decisions taken by the team in [Meeting Notes #13](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2313-09.05.2022)
- [ ] Support the Get method to get the content and process what it returns in JSON format.
- [ ] Support the Post method.
- [ ] Provide a front-end for an end-user. 
- [ ] Test your API using a tool like Postman. 
- [ ] Write unit tests for their code.
- [ ] Request for code review by creating pull requests. 
- [ ] Update the GitHub wiki page with a description of the API and the functionality I introduced.

## Place to put the documentation:
Push all work related to the assignment under a folder created in your repository (GitHub) called practice-app.

## Review:
TBA

## Deadline: 20.04.2022 - 23.59

**Comment by muhammetssen** [comment]
Not done :( Sorry

**Comment by ahmetkudu** [comment]
> @ahmetkudu why did you close this? Based on what is it closed?

I'm sorry hocam. I could not complete my part of the practice-app because of the insufficient knowledge of web programming. Really, I'm very sad about that this.

**Comment by ahmetkudu** [comment]
Due to my deficiencies in web programming, I could not do this assignment. I will close this gap until the next study.
