### ISSUE TITLE
[Practice App]: Implementing Post API

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#187]
## Task
For my part in the practice app, I will use [Gorest Api](https://gorest.co.in/) to implement a post searching  and post creating. Searching with a keyword that is related to user id and the user will be able to create a post. 

**Required endpoints** : 
- createPost is a POST method which, createa post
- getPosts is a GET method that gets the all posts of user.
- savePost is s POST method that save a post

## To Do
- [x] List of posts.
- [x] Document the research done.
- [x] Implement GET for users posts.
- [x] Implement POST for creating user post.
- [x] Implement POST method for creating user post in db.
- [x] Prepare a table in DB.
- [x] Design for post page 
- [x] Design for create and save post page
- [x] Document own work
- [x] Push all work related to the assignment under a folder created in your repository (GitHub) called practice-app.
- [x] Request for code review by creating pull requests. 

**Deadline:** TBD

**Comment by muhammetssen** [comment]
Done!
