### ISSUE TITLE
[Practice App]: Personal Effort Summary

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#228]
# Task
Each member will write a summary of their personal efforts during the development of the practice application (in tabular form). These will be collected under this issue as comments. Currently:

- [x] Burak Yılmaz
- [x] Arif Akbaba
- [x] Mehmet Gökberk Aslan
- [x] Bilal Aytekin
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [ ] Ahmet Kudu
- [x] Salim Kemal Tirit
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Bengisu Kübra Takkin

# Place to put the documentation
Practice App, Group Submission.

#### Deadline: 20.05.2022, 23:00

**Comment by ersoykadir** [comment]
## Kadir Ersoy
- Researched Auth0 API [#168](https://github.com/bounswe/bounswe2022group3/issues/168).
- Created users endpoint.
- Added Login and Register features [#212](https://github.com/bounswe/bounswe2022group3/issues/212), [#182](https://github.com/bounswe/bounswe2022group3/issues/182).
- Added getUsername feature [#214](https://github.com/bounswe/bounswe2022group3/issues/214).
- Created authorization middleware[239](https://github.com/bounswe/bounswe2022group3/issues/239).
- Created Main page[#213](https://github.com/bounswe/bounswe2022group3/issues/213).
- Wrote unit tests for users endpoint [#216](https://github.com/bounswe/bounswe2022group3/issues/216).
- Reviewed TweetAnalysis branch [pr](https://github.com/bounswe/bounswe2022group3/pull/199).
- Documented API using Swagger [#222](https://github.com/bounswe/bounswe2022group3/issues/222).
- Documented Users requirements [#217](https://github.com/bounswe/bounswe2022group3/issues/217).
- Designed Use Cases for users endpoint [#223](https://github.com/bounswe/bounswe2022group3/issues/223).
- Designed User Class [#223](https://github.com/bounswe/bounswe2022group3/issues/223).
- Designed Sequence Diagrams for "Users" use cases [#223](https://github.com/bounswe/bounswe2022group3/issues/223).
- Documented Project Plan using projectLibre [#215](https://github.com/bounswe/bounswe2022group3/issues/215).

**Comment by Goko6** [comment]
## Mehmet Gökberk Arslan
- Done research to learn and better understand the tools we are going to use for our implementation such as swagger, mongoDB and postman. The issue for the tools we have used: ([Issue#236](https://github.com/bounswe/bounswe2022group3/issues/236))
- Decided to implement a cryptocurrency conversion API and learned express.js, next.js in order to implement my part of the practice-app ([Meeting Notes 13](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2313-09.05.2022))
- Created requirements for the cryptocurrency functionality of the app ([Issue#226](https://github.com/bounswe/bounswe2022group3/issues/226))
- Created UML diagrams cryptocurrency part of the app (Use case, class, sequence) ([Issue#208](https://github.com/bounswe/bounswe2022group3/issues/208))
- Implemented the required frontend and backend for the cryptocurrency API ([Issue#169](https://github.com/bounswe/bounswe2022group3/issues/169))
- Implemented unit tests and prepared API documentation using swagger for the cryptocurrency API and then added them to my code ([Issue#209](https://github.com/bounswe/bounswe2022group3/issues/209))
- Created a pull request to merge my code into master ([Pull#225](https://github.com/bounswe/bounswe2022group3/pull/225))
- Attended all group meetings related to practice-app except one.

**Comment by nurlandadashov02** [comment]
## Nurlan Dadashov
- Developed initial setup for backend [#153](https://github.com/bounswe/bounswe2022group3/issues/153).
- Developed initial setup for frontend [#154](https://github.com/bounswe/bounswe2022group3/issues/154).
- Researched public chess APIs - Lichess API [#156](https://github.com/bounswe/bounswe2022group3/issues/156).
- Developed backend for game creation [#157](https://github.com/bounswe/bounswe2022group3/issues/157).
- Developed frontend for game creation [#158](https://github.com/bounswe/bounswe2022group3/issues/158).
- Developed backend for playing chess game [#161](https://github.com/bounswe/bounswe2022group3/issues/161).
- Developed frontend for playing chess game [#162](https://github.com/bounswe/bounswe2022group3/issues/162).
- Developed backend for previous chess game [#163](https://github.com/bounswe/bounswe2022group3/issues/163).
- Developed frontend for previous chess game [#164](https://github.com/bounswe/bounswe2022group3/issues/164).
- Researched Express unit testing and Developed unit tests for the server code [#177](https://github.com/bounswe/bounswe2022group3/issues/177).
- Documented endpoints using Swagger [#201](https://github.com/bounswe/bounswe2022group3/issues/201).
- Documented User and System requirements for Chess [#186](https://github.com/bounswe/bounswe2022group3/issues/186).
- Documented Non-functional requirements [#185](https://github.com/bounswe/bounswe2022group3/issues/185).
- Designed Use case/Class/Sequence Diagrams for Chess feature [#202](https://github.com/bounswe/bounswe2022group3/issues/202).
- Attended all team meetings.

**Comment by muhammetssen** [comment]
## Muhammet Şen
* Implementing endpoints for managing stream rules [#171](https://github.com/bounswe/bounswe2022group3/issues/171)
* Implementing endpoints for managing stream rules [#172](https://github.com/bounswe/bounswe2022group3/issues/172)
* Analyzing tweets' average text lengths and number of words [#173](https://github.com/bounswe/bounswe2022group3/issues/173)
* Integrating Swagger for Express [#178](https://github.com/bounswe/bounswe2022group3/issues/178)
* Unit testing tweetSearch endpoints [#183](https://github.com/bounswe/bounswe2022group3/issues/183)
* Designing Class Diagrams [#188](https://github.com/bounswe/bounswe2022group3/issues/188)
* Use Case/ Class/ Sequence Diagrams for Tweet Analytics [#203](https://github.com/bounswe/bounswe2022group3/issues/203)
* Containerization of the application[#220](https://github.com/bounswe/bounswe2022group3/issues/220)
* Documenting User and System Requirements for Tweets  [#233](https://github.com/bounswe/bounswe2022group3/issues/233)
* Writing Executive Summary [#234](https://github.com/bounswe/bounswe2022group3/issues/234)

**Comment by bilalcim** [comment]
## Bilal Aytekin
- Researched [TheMovieDB API](http://api.themoviedb.org).
- Researched the tools in [#236](https://github.com/bounswe/bounswe2022group3/issues/236).
- Created the movies endpoint.
- Covered Issue [#174](https://github.com/bounswe/bounswe2022group3/issues/174).
- Documented API using Swagger [#222](https://github.com/bounswe/bounswe2022group3/issues/222).
- Documented requirements for the movies endpoint [#207](https://github.com/bounswe/bounswe2022group3/issues/207).
- Designed use case, class and sequence diagrams for the movies endpoint [#247](https://github.com/bounswe/bounswe2022group3/issues/223).

**Comment by yilmaz-burak** [comment]
## Burak Yilmaz
- Created a release for the practice-app #248 
- Created class diagrams for currency #246
- Created use case diagrams for currency #245 
- Created sequence diagrams for currency #198 
- Documented user and system requirements for currency #197 
- Reviewed the pr #180
- Reviewed the pr #221
- Documented API by Swagger for currency #194
- Created unit tests for currency #192 
- Created backend for currency #191 
- Created frontend for currency #190 
- Attended all team meetings.

**Comment by mertcan-ozkan** [comment]
## Mertcan Özkan
- Researched [TheMovieDB API](http://api.themoviedb.org).[#227](https://github.com/bounswe/bounswe2022group3/issues/227).
- Researched the tools in [#236](https://github.com/bounswe/bounswe2022group3/issues/236).
- Created the articles endpoint. [#240](https://github.com/bounswe/bounswe2022group3/issues/240)
- Documenting User and System Requirements for Artciles [#240](https://github.com/bounswe/bounswe2022group3/issues/240)
- Designed use case, class and sequence diagrams for the movies endpoint [#247](https://github.com/bounswe/bounswe2022group3/issues/223).
- Attended all team meetings.

**Comment by arfakbaba** [comment]
## Arif Akbaba
- Done research to learn and better understand the tools we are going to use for our implementation. [#187](https://github.com/bounswe/bounswe2022group3/issues/187)
- Decided to implement a post API and learned express.js, next.js in order to implement my part of the practice-app ([Meeting Notes 13](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2313-09.05.2022))
- Created requirements for the post functionality of the app [#226](https://github.com/bounswe/bounswe2022group3/issues/229)
- Created UML diagrams post part of the app (Use case, class, sequence) [#218](https://github.com/bounswe/bounswe2022group3/issues/218)
- Implemented the required frontend and backend for the post [#187](https://github.com/bounswe/bounswe2022group3/issues/187)
- Implemented unit tests ([#232](https://github.com/bounswe/bounswe2022group3/issues/232)
- Prepared API documentation using swagger for the gorest API and then added them to my code ([#231](https://github.com/bounswe/bounswe2022group3/issues/231)
- Created a pull request to merge my code into master [Pull#200](https://github.com/bounswe/bounswe2022group3/pull/200)
- Attended all group meetings related to practice-app except one.

**Comment by hsuleerkul** [comment]
## Hatice Şule Erkul
* Researched about different free APIs, after that I chose [Open Trivia DB API](https://opentdb.com/api_config.php)
* Wrote user and system requirements [#242](https://github.com/bounswe/bounswe2022group3/issues/242)
* Created class, use case and sequence diagrams [#235](https://github.com/bounswe/bounswe2022group3/issues/235)
* Implemented endpoints : [#170](https://github.com/bounswe/bounswe2022group3/issues/170) & [PR](https://github.com/bounswe/bounswe2022group3/pull/230#partial-pull-merging)
  * `/quiz/categories`
  * `/quiz/new_quiz`
  * `quiz/view/all`
  * `quiz/view/[quiz_id]`
* Implemented unit tests for the endpoints.  [#210](https://github.com/bounswe/bounswe2022group3/issues/210)
* Done API documentation on Swagger  [#211](https://github.com/bounswe/bounswe2022group3/issues/211)

**Comment by Brunettow** [comment]
# Bengisu Takkin
- Created a release for the practice-app 
- Created class diagrams for Email Verifier #251
- Created use case diagrams for Email Verifier #251
- Created sequence diagrams for Email Verifier #251
- Documented user and system requirements for Email Verifier #206
- Reviewed @bilalcim's [API (TheMovieDB API)](http://api.themoviedb.org/) #174
- Documented the API by Swagger for Email Verifier #204
- Created unit tests for Email Verifier #205
- Created backend for Email Verifier #175
- Created frontend for Email Verifier #175
- Attended all team meetings

**Comment by salimtirit** [comment]
* Researched about different free APIs, after that I chose [Genius](https://docs.genius.com/)
* Created class diagrams for Lyrics 
* Created use case diagrams for Lyrics 
* Created sequence diagrams for Lyrics 
* Documented user and system requirements for Lyrics 
* Reviewed @Brunettow 's [API (Email Verifier)]() 
https://github.com/bounswe/bounswe2022group3/issues/175
* Documented the API by Swagger for Lyrics
* Created unit tests for Lyrics 
* Created backend for Lyrics 
* Created frontend for Lyrics 
* Attended team meetings

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
