### ISSUE TITLE
Tracking Weekly effort of Week 10 - 11

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#257]
All the team members should report their weekly efforts for [week 10](https://github.com/bounswe/bounswe2022group3/wiki/Week-10-Personal-Efforts) and [week 11](https://github.com/bounswe/bounswe2022group3/wiki/Week-11-Personal-Efforts).

So far:
- [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Burak Yılmaz
- [x] Salim Kemal Tirit
- [x] Mertcan Özkan

Deadline: 24.05.2022,10:00

**Comment by ersoykadir** [comment]
Done!
