### ISSUE TITLE
Requirements review

### ISSUE THREAD

**Issue by furkanakkurt1335** [bounswe/bounswe2022group3#258]
Requirements should be reviewed by everyone and corrected accordingly. Deadline: 10/11/22.

## Task

All the members need to review the [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) and update them. Please ask any questions regarding them if unsure. If you have a not-so-small update, please comment your reasons under this issue for documentation. 

- [x] Burak Yılmaz, @yilmaz-burak 
- [x] Arif Akbaba, @arfakbaba 
- [x] Mehmet Gökberk Arslan, @Goko6 
- [x] Bilal Aytekin, @bilalcim 
- [x] Nurlan Dadashov, @nurlandadashov02 
- [x] Hatice Şule Erkul, @hsuleerkul 
- [x] Kadir Ersoy, @ersoykadir 
- [x] Salim Kemal Tirit, @salimtirit 
- [x] Mertcan Özkan, @mertcan-ozkan 
- [x] Muhammet Şen, @muhammetssen 
- [x] Furkan Akkurt, @furkanakkurt1335 
- [x] Berke Özdemir, @berkeozdemir2016400246

**Comment by yilmaz-burak** [comment]
We should update annotations --> Clear vagueness... People should be able to see the annotations on the phrases/words/sentences etc... Hide/show could be implemented...

**Comment by furkanakkurt1335** [comment]
I'd gone over the [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) on [10/8](https://github.com/bounswe/bounswe2022group3/wiki/Week-1-between-03.10.22-and-09.10.22-for-Personal-Efforts#furkan-akkurt). 

Some places that standed out to me:

## 1. Glossary

> Communication channel: A platform users can use to get in touch.

It's not clear who is being gotten in touch with.

## 2. 1.1.2.4.

> .. by clicking Forget Password button

This is very specific. I'm not sure we need to specify the text of the button. _by clicking_ should be enough.

## 3.4.1.

> The platform shall respond in at most 3 seconds.

It's not clear to me what the platform responds to.

**Comment by furkanakkurt1335** [comment]
## 2.6.3.

> The system shall provide a mechanism such that annotation can be applied to any context.

This seems very open to speculation. I would recommend narrowing it down, regarding the context; or including what _context_ means in the glossary.

**Comment by mertcan-ozkan** [comment]
here is my review:
#### Glossary : Interface
"Interface: The graphical platform provided by this application to supply users with ease of use."
- I am not sure if this sentence is grammatically correct.
#### Glossary :event and meeting  
- I think we should define these better. Right now, it is hard to differentiate them by their definitons.
#### Glossary :Note Taking: The act of recording information.
- I think this sentence is too vague.
#### Glossary: Prerequisite Course |||| 1.3.7. Users shall enroll to any course they want to.
- From the definiton of  Prerequisite Course, users are not allowed to enroll a course if they have not taken the prerequisite, these two look like they contradict with each other. 
#### 1.1.2.5 and 1.3.10.
1.1.2.5. Users shall be able to change their password by using the profile settings page.
1.3.10. Users shall be able to change their password by visiting the settings on the profile page.
- these two tell the same thing. Maybe we could edit one of the two.

**Comment by nurlandadashov02** [comment]
1. 1.1.1.2. Users ~shall~ _should_ be able to register using their ~Facebook, Twitter or~ Google accounts.
2. 1.1.2.2. Users ~shall~ _should_ be able to log into their account using their ~Facebook, Twitter or ~Google account (if they have previously completed 1.1.1.2.).
3. 1.1.2.4. Users ~shall~ _should_ be able to reset their password via email verification by clicking ~Forget Password~ _a_ button.
4. 1.1.2.5. Users ~shall~ _should_ be able to change their password by using the profile settings page.
5. 1.3.8.1. Lecturers shall be able to create polls, allowed to be filled by the students enrolled in their course. The anonymity ~and/or the obligation~ of the poll shall be decided by the lecturer and declared to the students.
6. 1.3.8.2. Lecturers shall be able to organize and schedule events. The scope of the event depends on the lecturer's initiative. It can be ~public or private~ (instead may limit by capacity (FCFS)), face-to-face ~or online, free or with a fee to enter~.
7. ~1.3.8.2.1. If the event is private, the lecturer shall have to provide the list of learners who can attend the event. These users shall be notified.~
8. 1.3.8.3. The lecturer shall have the right to edit details (date/time, title, description, location, quota, ~list of attendees, fee~) of the event.
9. ~1.3.10. Users shall be able to change their password by visiting the settings on the profile page.~
10. 2.1.2.2.2. The system shall keep a predefined list of badges that can be earned by a user. (?)
11. 2.1.2.2.3. Users will gain a badge when one _of_ the following occurs: a learner completes a course, a learner completes one section of the course (same badge or what?), a lecturer opens a new course, and ~a lecturer receives a review point that is greater than 4. (see 2.1.2.7.2.)~ 
12. What is considered "completing a section of a course"?
13. 2.1.2.3.2.1. The system shall promote (?) users to choose from this list to define their interests.
14. 2.1.2.3.2.2. Interests page shall be created based on the selections of a user from this list. (?)
15. 2.1.2.4.3. The system shall update the activities page when at least one of the following happens: a learner joins an ~meeting~ event, a learner completes a course or a section of it, a learner enrolls in a new course, a learner drops a course or a learner attends a quiz (anonymous ?).
16. 2.1.2.4.4. The system shall update the activities page when at least one of the following happens: if a user is ~also~ a lecturer in a course, the lecturer arranges ~a meeting~ _an event_ ~or joins one~, the lecturer opens a new course, the lecturer closes a course or the lecturer opens a quiz for ~one~ _a_ course.
17. ~2.1.2.5.4. If a user is also a lecturer, the following statistics shall be kept by the system about each course that the user gives: how many users have enrolled in the course, how many users have completed the course, how many users have dropped the course and how many users have attended which quizzes of a course.~
18. 2.1.2.6. Knowledge (What is knowledge and how is it different from interests, why do we need it, how will we use this?)
19. 2.1.3. Following (More requirements needed. How to send follow request? Accept/decline follow request. Public profile auto accept follow request. Do we even have to have private profiles?)
20. 2.2.3. The system ~should~ shall support sharing resources and files.
21. 2.3. Note Taking (Need to reconsider note taking. Shall notes be tied to profile or to specific course. How is note taking actually performed? Relation to annotations?)
22. 2.3.4. The system shall provide learners the ability delete or rearrange (?) their note taking pages.
23. The system shall provide registered learners the ability to connect, annotate and tag notes. (How to connect or annotate note?)
24. The system shall provide learners the ability to share their notes with others. (individually or linked according to their choice?)
25. ~2.4.1.1 The system shall provide learners the option to mark courses in the recommendations list as "not interested".~
26. 2.4.2. The system shall rank courses that are similar (?) to recently completed courses of the learner, courses that have the learner's previously completed courses as prerequisites and courses that are related to the learner's area of interests higher in the recommendations list.
27. 2.5.5. The notes belonging to and shared with a user ~shall~ should be searchable.
28. ~2.5.6. It shall be possible to sort the results from newest to oldest or oldest to newest.~
29. ~2.5.7. The system shall provide filtering of search results.
2.5.7.1. The system shall provide filtering on the course results according to the availability of in-person meetings.
2.5.7.2. The system shall provide filtering on the discussion channel search results according to topic.
2.5.7.3. The system shall provide filtering on the results according to date.~
30. 2.6.1. The system shall support annotating with text, images (?) and URI.
31. 2.6.2. The system shall support links that relate to semantic resources about the resource. (?)
32. 2.6.3 The system shall provide a mechanism such that annotation can be applied to any context. (?)
33. ~3.3.6. The system shall have two options for the visibility setting of a user profile:
3.3.6.1. Public Profile: The system shall allow other users to see a user's profile if the user opts to choose the public profile option.
3.3.6.2. Private Profile: The system shall not allow other non-follower users to see a user's profile if the user opts to choose the private profile.
3.3.6.3. Additionally, users blocked by another user shall be prevented to interact with the user who blocked them and both parties shall not view any page related to each other.~ (Do we need this?)

**Comment by berkeozdemir2016400246** [comment]
Here is my review:
>1.1.2.3. If a user enters their password wrong three times while logging in, they shall reset their password using their email.

This seems like a security risk to me considering all you need to force a new password on someone else(as a malicious agent) is to know their email and simply attempt 3 password entries. 

>1.3.8.2.1. If the event is private, the lecturer shall have to provide the list of learners who can attend the event. These users shall be notified.

If there is an in-platform notifications system we should add it to the requirements.

>1.4. Admin User

We need to expand these. Do they have access to all (or any) normal user functionalities? (Creating a course, attending a course, changing password, making annotations). Do they have profile pages? 

>2.1.2.2.4. The system shall allow a lecturer to add more badges to the badge list of the course they created.

How are those new badges different from the ones defined in 2.1.2.2.3? Do they crate rulesets to automatically manage badges (x number of annotations made) or do they manually give them?

>2.1.2.7. Rating

If we plan to show this anywhere, we should specify in the requirements.

>2.4.2. The system shall rank courses that are similar to recently completed courses of the learner, courses that have the learner's previously completed courses as prerequisites and courses that are related to the learner's area of interests higher in the recommendations list.

Prerequisite system is only mentioned in here and in the glossary. We should at least mention how they are created and by whom.

>(from glossary) Reputation: Degree of a lecturer's past achievements, experience and influence on others.

We should specify how reputation is determined.

**Comment by berkeozdemir2016400246** [comment]
Sorry did not mean to close the task

**Comment by muhammetssen** [comment]
@ersoykadir and I worked together and created a merged list of reviews.
 
- 1.3.4 should include note taking features directly since current situation is not easy to read
- 1.1.1.2 and 1.1.2.2. We can remove Twitter and Facebook login, just Google would be enough
- We can add:
    - 3.2.3 The system shall invalide the passwords that have been entered incorrectly three times in a roe
- 1.3.1 Definition of blocking should be more  elobarete.
    - 1.3.1.1 Blocked users shall not be able to view the blocking user’s profile, enroll to their courses, and comment on discussion posts they have created.
- 2.1.3.2. The system shall allow a follower of a user to see the following features of a profile: achievements, monitoring, interests, knowledge, bio, activities, notes and annotations.
- We can remove 2.2.2 since it’s very similar to 2.2.1 and threading and mentioning are too cumbersome to properly deliver.
- 2.3.3.1 Definition of popularity is not clear. We can substitute the popularity word with number of views, for the sake of simplicity.
- 2.3.3.2 What does previous mean?
- 2.3.4 Rearranging notes is not applicable for our case. Edit would be a better adjective than rearrange.
    - 2.3.4. The system shall provide learners the ability edit or delete their notes.
- 2.3.5 What is connecting notes?
- 2.3.6 The system shall support viewing notes of public and followed users on their profiles. The same functionality applies for sharing notes’ links.
- 2.3.7 The system shall provide the ability to get a copy of another user’s note to their own profile with indicating the original author, like forking a github repository
- 2.4.1.1 How are we going to implement this? This is too ambitious for this project.
- 2.5.3.1 How do we define similarity in here? 2.5.3.2 is enough for defining similarity.
- 2.5.3.3 Again, too advanced for our project!
- 2.5.4 We can just search in the first post’s title and description. Searching in comment should be out of our scope.
- 2.5.5 Searching in shared notes is more complicated than it sounds. Searching in user’s own notes should be enough.
- 2.6.1 There is no need to have images in annotations. Also, URL is just plain text no need to specify   How to make an annotation is not clear
    - User shall select a portion of the text and annotate
    - User should be able to turn on and off annotation visibility
    - System - Annotated text portions shall be highlighted to emphasize annotation
- 2.6.2 How are we going to do that
- 2.6.3 context = notes and course content
- 1.1.2.5 and 1.3.10 are the same
- Do we have custom badges?
- 2.1.2.2.3 Giving.a badge to lecturers for reviews is unnecessary since we already have lecturer reputation system via rating.
- 2.1.2.2.4 Should we have custom badges? We think there should only be badges for chapter and course completion
- 2.1.2.3 How to define the predefined interests?
- 2.1.2.6.2 Definition of knowledge in glossary is vague. Instead of knowledge, we can have section for completed courses which would show the knowledge of the learner.
- 2.1.2.7.2.1 We shall display number of rates given with the average rate score
- 2.4 Course recommendations should based on matching course topics with  a list of user interests plus previously completed courses’ topics. We can store not only the name of the topics but also how many times that topics occur.
- We should remove prerequisites completely from the platform.

**Comment by arfakbaba** [comment]
Glossary;
- Popularity and Rating have similar meanings. These can be more descriptive or we can just use one.

 Requirements;
>  1.1.2.3. If a user enters their password wrong three times while logging in, they shall reset their password using their email.

If there will be a forgot password button. There is no need for this requirement. However, the system can send e-mails such as "Are you the one who wants to access this account?"

>   2.1.2.5.3. If a learner drops a course, their monitoring record shall be deleted.

Will the user be able to see the previous monitoring records if he/she retakes the lesson he/she has left in the future?
> 2.4.2. The system shall rank courses that are similar to recently completed courses of the learner, courses that have the learner's previously completed courses as prerequisites and courses that are related to the learner's area of interests higher in the recommendations list.
 
 Here recommadation can be based on user's interests.

**Comment by bilalcim** [comment]
- Chapter: A part of a course that consists of course contents, if a user completes a chapter, that has a badge ~they will receive a badge~ which they will receive.
- Course Content: A part of a course that consists of a part of the course material. It can be only text. ~or supported with audiovisual media.~ (We are turning away from media content.)
We do not mention blocking, yet we had discussed and decided to implement it. In accordance with that, the "every user" part of the following item from the glossary should be changed:
- A profile page that every user of the application can view.

**Comment by yilmaz-burak** [comment]
1.2.1 --> Exclusive to themselves?
1.3.1 --> Blocking users meaning?
1.3.8.3 --> Editing event details should be limited. For example, editing time shouldnt allow for a past time and so on...
1.3.8.4 --> Cancel should be conditional. There should be some criteria added...
1.3.11 --> They should be able to join conditionally (ie, if the quota is full or any criteria isnt met, they might not be able to join the attendee list)
1.4.2 --> What are Inappropriate comment and articles ?

2.1.1 --> What sort of structure can they edit?
2.1.2.2.2 --> I dont think we system should hold predefined list of items. It can simply hold the earned badges.

2.2.3 --> what kind of resources and files?
2.5.3.1 --> Similar is an ambiguous word. I think we should just show the already taken courses at the top. Other than that, remaining 'relevant' courses can be shown if they are semantically similar - without any sort of ordering-
2.5.3.2 & 2.5.3.3 --> Similar to 2.5.3.1, keeping relevance is not that beneficial, weighted against the work it requires.
2.6.3 --> Any context is ambiguous. We should explicitly state what it is.

3.1.1 --> No need to state `native` android application

**Comment by salimtirit** [comment]
My review of the requirements

Glossary:
Annotation:  Content referring to some other resource --> vague
Badge: The thing  ??
Chapter: not a definition more like a sentence
Communication channel: might need to be removed
Course content: supported with audiovisual media part needs to be removed
Feedback: user should be enrolled or finished the course
Geolocation: of the user or an event
Lecturer: admin privilege or not
note taking: ??
meeting: ??
recommendation: not a definition more like description
tag: ***

User Requirements:
1.1.1.1.1. got into the implementation part
1.1.2.4  got into the implementation part
1.1.2.5 ????  got into the implementation part (?)

1.3.8. Users shall be able to open a course in any subject and they don't need to provide any document regarding their experience on the topic. (-----after here might not be necessary.) The user shall become the lecturer of the course s/he opened.
1.3.10 got into the implementation part

2.1.2.2.2 what does predefined mean.

**Comment by yilmaz-burak** [comment]
Thank you everyone for your reviews. We have opened an issue #269  to take action on these. Closing for now...
