### ISSUE TITLE
Mockup and Diagram Reviews

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#259]
### Task
All team members need to review the [mockups](https://github.com/bounswe/bounswe2022group3/wiki/User-Scenarios-and-Mockups) and design products such as [use case](https://github.com/bounswe/bounswe2022group3/wiki/Use-Case-Diagrams), [class](https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams), and [sequence diagrams](https://github.com/bounswe/bounswe2022group3/wiki/Sequence-Diagrams). These will be collected here as comments. The reason why we do this here is essentially to document our communication.

- [x] Arif Akbaba
- [x] Furkan Akkurt
- [x] Mehmet Gökberk Aslan
- [x] Bilal Aytekin
- [ ] Nurlan Dadashov
- [ ] Hatice Şule Erkul
- [x] Kadir Ersoy
- [ ] Berke Özdemir
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [ ] Salim Kemal Tirit
- [x] Burak Yılmaz

**Deadline:** October 12, 13:00.

**Comment by furkanakkurt1335** [comment]
In the user scenario of [Event Creation](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1), there is a link to an issue, I guess aiming to describe the criteria of the event:

> website (according to these [criterias](https://github.com/bounswe/bounswe2022group3/issues/25)), announcing  

I don't think we should link to an issue. Maybe, we can include the criteria in the user scenario, if necessary; otherwise, delete the criteria altogether.

**Comment by furkanakkurt1335** [comment]
I've gone over all the user scenarios and their mockups. I changed some requirements in the _Acceptance Criteria_ sections to match them with the requirements in the actual requirements page but they are not functional changes.

I also changed the order of the web and mobile mockup images in the 2nd user scenario as the mobile was the first mockup in the page. It seems the other way around is the convention (if 2 examples can be a convention over 1).

**Comment by furkanakkurt1335** [comment]
In the mockups of the [user scenario 3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3), I see the user taking notes while a lecture video is open. I remember talking about this in the last meeting (10/4) in the lab: annotating specific video sections. The mockups do not allude to this. It seems that the user only takes notes of text and no mention of timestamps are in the images. I don't recall any requirements mentioning this also. So annotations of specific places of a lecture is not included anywhere already, right?

**Comment by mertcan-ozkan** [comment]
here is my review:
#### Use Case Diagram
- Tag of the arrows going out of “manage course”, “view  course content” and “attend course” is missing. <“includes”> tag should be added to them.
- Cases that extend “comment to a post” are very vague. For instance “delete” can be changed into “delete previously created post”.
#### Class Diagram
- In emailservice, there is a function that is crossed out. We should remove that if it is not going to be included.
#### Mockups
- In scenario 3, user saves a note in the video, this scenario needs to be changed if we are not going have videos on our app.

**Comment by yilmaz-burak** [comment]
#### Mockups:
- Depending on the outcome of the discussion of having videos on the platform, we may need to update the mockups reflecting that change.

#### Use Case Diagram
- Some tags are missing in the arrows, such as the ones coming from Admin. Also the bold ones do not have those tags as well.

#### Class Diagram
- We have services in the class diagram, which are actually collection of functions that do not have an entity on the database. We could reflect that in a better way I believe.

#### Sequence Diagram
- A small thing, all the images should be in the format of a png i believe, not having the background guidelines.
- Some object are shown as classes, some are objects of classes. This should be normalized in all of the diagrams. (ie. `Chapter` vs `chapter:Chapter`)

**Comment by muhammetssen** [comment]
## Use Case
- Linking another note is not in requirements, we can remove from use case diagram
- Poll use case diagrams indicates features like selecting poll mode, duration etc.; however, requirements shall include those.
- Comment to a discussion - we can remove threading 

## Class Diagram
- Chapters has badge property, we can use chapters to get all badges related to a course. We can remove `course_badges` field from `Course` class.
- Linking notes is not easy to implement
- Notes' public and privates status can be fetched from the user's profile. That way, note can be viewed if the profile is public or user is followed by the viewer. Downside of this approach is user cannot make some notes public and some notes private.

**Comment by ersoykadir** [comment]
## Use Case
- **Manage Content** use case, Add video and picture cases should be eliminated.
- **Search** use case, we should add search notes.
- **Course content** use case, we don't have public notes on courses. Notes are related to users and can only be viewed on profiles.

## Class Diagram
- **CourseContent** class has a media field. It should be removed if we will avoid media content.
- **PersonalInformation**, knowledge field may be transformed to completed courses list.
  - We don't have activities class, so we need to have one. It should store user, date, activity content text. User activities should be triggered by course or chapter completion.
 
## Sequence Diagram
- We might need to update Ahmet's discussion sequence, if we will remove threading.

**Comment by Goko6** [comment]
## Sequence Diagram
- **Creating Discussion** mockups will need a change such that every chapter of a course will have its own seperate discussion and threading will probably get removed.

**Comment by arfakbaba** [comment]
## Use Case
- Manage Notes use case,  Add content can be removed.
- Manage Poll use case, We can removed poll mode, The description, duration and answers required are sufficient when creating the poll.


## Class Diagram
-  Quiz mode can be removed in poll class.

**Comment by bilalcim** [comment]
### Mockup 1

- There are unanswered questions in the [event set up requirements](https://github.com/bounswe/bounswe2022group3/issues/25) issue attached to the mockup:
   - I do not think there should be a fee option for events, we aim for a free environment.
   - Having an upcoming events section is a wonderful idea! It sets off the right motivation for the lecturer to keep her course active because this section would be a way to attract more people to the course.
   - Another statement of freedom is to let anyone organize an event, and to let the lecturer cancel the event whenever she feels comfortable, e.g. when the attendance is low.
- Shouldn't Yone set the meeting capacity to be the theatre's capacity?

### Use-Case Diagrams

- `Create Poll` includes setting a duration and a poll mode, yet these are absent in Mockup 1.
- `View User Profile Page` lacks viewing the rating (see, [Requirements 2.1.2.7](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#system-requirements)).
- User-user interactions like following and blocking are missing.

### Sequence Diagrams

1. Register to an Event
   - On `getEvent()`, the database should return a single event, not a list of events.
2. Modify a Badge
   - I did not really understand the use-case, but shouldn't the `getBadgeID()` method accept some parameters?

**Comment by ersoykadir** [comment]
The Design updates related to both these comments and newly decided changes are distributed among team members and accomplished in #329, #330, #333 issues. So this issue can be closed.
