### ISSUE TITLE
Organizing Wiki homepage

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#266]
### Issue

Our wiki homepage does not have direct links to some documents we have prepared previously like project plan and RAM. 

### Task(s)

- [x] Add project plan to wiki homepage
- [x] Add RAM to wiki homepage
- [x] Add project desings to wiki homepage

### Deliverable(s)

Updated wiki page

### Acceptance Criteria

-

### Deadline of the issue

11.10.2022

### Reviewer

Kadir Ersoy

**Comment by muhammetssen** [comment]
You can see the updated wiki page [here](https://github.com/bounswe/bounswe2022group3/wiki)

**Comment by ersoykadir** [comment]
Well done!
