### ISSUE TITLE
Deploy sample app locally

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#275]
### Issue

We need to be able to see that our setups are correct and we can develop reliably locally. For that, every backend team member will deploy the sample apps locally.

### Task(s)

- [x] Deploy locally - @ersoykadir
- [x] Deploy locally - @furkanakkurt1335
- [x] Deploy locally - @Goko6 
- [x] Deploy locally - @yilmaz-burak 

### Acceptance Criteria

* Successfully deploy sample apps.

### Deadline of the issue

19.10.2022 @23.59

**Comment by ersoykadir** [comment]
Done, reviewed in meeting.
