### ISSUE TITLE
Organizing Wiki Side Bar and Main Page 

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#280]
### Issue

There is a need to update the wiki side bar and main page to be able to access the documents of 451 course and the subteams more easily. Currently, every meeting note is under `352` and `451` titles without a categorization. The former team members should be specified to clear any confusion. My goal is a clean looking wiki page. 

### Task(s)

- [ ] Move `Practice App` related sections to the bottom of the sidebar and main page. 
- [ ] Move `352` related sections to the bottom of the sidebar and main page. 
- [ ] Categorize `Meeting Notes` section for mobile, fronend and backend teams and update their titles in the sidebar and main page. 
- [ ] Update `Team Members` section of the sidebar, specify former members.

### Deliverable(s)

* ...
* ...
* ...

### Acceptance Criteria

* Update both the sidebar and main wiki page.

### Deadline of the issue

20.10.22 @23.00
