### ISSUE TITLE
Setting Up The Flutter Environment

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#283]
### Issue

We decided to use Flutter for the mobile part of our project.  I have not used Flutter before therefore I need to set up the environment for Flutter, try some basic things, and get used to it. 

### Task(s)

- [x] Installing and setting up the flutter
- [x] Installing android studio
- [x] Learning how to run and debug using android studio. 
- [x] Learning about android emulators

### Acceptance Criteria

* Feeling comfortable

### Deadline of the issue

20.10.2022 @23.59

### Reviewer

Salim Tirit

### Deadline for Review

20.10.2022 @23.59

**Comment by salimtirit** [comment]
I feel comfortable using flutter now.
