### ISSUE TITLE
Learning Flutter and Running Initial Mobile App

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#284]
### Issue

I started setting up the flutter environment. After I finish setting up I need to learn the syntax and basics of flutter to get started with the app. I will start by reading some docs and watching videos and then I will read the code that is written by @muhammetssen. I will try to understand and run the code in issue #281 

### Task(s)

- [x] Learning flutter basics
- [x] Reading initial code
- [x] Running initial code

### Deliverable(s)

* ...
* ...
* ...

### Acceptance Criteria

* Learning flutter

### Deadline of the issue

21.10.2022 @23.59

### Reviewer

Salim Tirit

### Deadline for Review

21.10.2022 @23.59

**Comment by salimtirit** [comment]
I think I have some idea about flutter now.
