### ISSUE TITLE
[Frontend]: Registration/Login/Confirmation email pages

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#287]
### Issue

We need to add registration and login pages. These pages should validate user input and make requests to the server.

We need page that would open when confirmation link sent to user's email after registration is opened. The page would input user's email and send email and token to server to verify account.

### Task(s)

- [x] Write Frontend code for registration page
- [x] Write Frontend code for login page
- [x] Write Frontend code for confirmation page
- [x] Add requests to the server

### Deliverable(s)

* Frontend code for all pages

### Acceptance Criteria

* 1.1.1.1. Users shall be able to register using a valid and unique email address, a username, and a password as defined in the security section.
* 1.1.2.1. Users shall be able to log into their account using their email and password combination.
* 1.1.1.1.1. Users who are registered by providing their emails shall confirm their accounts via the link sent in the confirmation email.

### Deadline of the issue

28.10.2022 @17.00

### Reviewer

Berke Özdemir

### Deadline for Review

29.10.2022 @23.59

**Comment by nurlandadashov02** [comment]
Made initial commit for the pages. Currently no requests to backend.
https://github.com/bounswe/bounswe2022group3/pull/277

**Comment by nurlandadashov02** [comment]
Backend requests added: #309

**Comment by nurlandadashov02** [comment]
Pull request has been approved and merged
