### ISSUE TITLE
[Mobile] Home and search course pages

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#295]
### Issue

BUcademy needs a home and search course page. These are the first pages a user will see while using BUcademy so they should be easy to follow and comprehensive.

### Task(s)

- [x] Mock results since backend is not ready yet
- [x] Create a homepage
  -  [x] Add enrolled courses in a horizontal list 
  -  [x] Add top courses in BUcademy in a horizontal list
- [x] Create a search page 
  -   [x] List results

### Deliverable(s)

* Homepage that contains two lists, enrolled and top courses
* Searchbar that can be used to search courses for a given keyword. For now, search will only consider courses' names.

### Acceptance Criteria

- Being able to list enrolled courses
- Being able to list top courses
- Being able to search a course by its name

### Deadline of the issue

23.10.2022 @23:59
