### ISSUE TITLE
Learning Flutter

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#299]
### Issue

After our [meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231-19.10.2022-Mobile-Team), I have completed setting up the Flutter and Android Studio. I can read and understand what the code in our repo does however I lack the foundation to write functional code in Flutter, therefore I need to read its documentation and watch some tutorials. 
I create this issue to record my progress and list some resources that I might find useful later. 

### Task(s)

- [x] Read Flutter documentation
- [x] Find/watch beginner tutorials
- [ ] List resource links under this issue

### Deliverable(s)

* Video / documentation links under this issue

### Acceptance Criteria

* Starting coding process!

### Deadline of the issue

26.10.22 @23.00

**Comment by hsuleerkul** [comment]
Flutter docs : https://docs.flutter.dev/development/ui/widgets-intro
I have watched the videos from the previous chapters of the Flutter doc, and I have started doing some coding!
