### ISSUE TITLE
[Backend]: Registration, Login, Authorization

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#302]
### Issue

I will implement the registration/login and authorization systems. Basically I need to have functionalities to create user, authenticate them and authorize them.
- Authenticate: Login, confirming who user is
- Authorize: Giving permission to access resources.

### Task(s)

- [x] Create the `/register` endpoint.
  -  Given input, I need to hash the password and save the user to DB.
  -  Also we will send user a confirmation email, but this will be implemented by @yilmaz-burak.
```jsx
// POST request
register({
  'email': 'muhammet.sen@boun.edu.tr',
  'name': 'Muhammet',
  'surname': 'Sen',
  'password': 'PassWord123',
}) -> 
{
  'result': 'EMAIL_SENT' // we can translate 'EMAIL_SENT' to 'Success! Please check your inbox to confirm your account.
}
```
- [x] Create `/login` endpoint.
  - Check if user exists in our Db.
  - If so, get its password hash.
    - Hashing done with crypto library, used sha256 algorithm.
  - Create a hash with given password.
  - Compare the hashes.
  - If we have matching passwords, create access and refresh tokens and return.
```jsx
// POST
login({
  'email': 'muhammet.sen@boun.edu.tr',
  'password': 'PassWord123'
}) -> 
{
  'id': '634cf129a727c14722a631fa',
  'email': 'muhammet.sen@boun.edu.tr',
  'accessToken':'UhuXWQvPLQW2qK93d0MaDJzGl8N',
  'refreshToken': '7yG2A55KWYw6LjAvCRwbNmw48bTw3O2CHO3K5fUHCk4Ad7ulCq'
}
```
- [x] Handle token generation.
  - We will use JWT tokens. There is js library for creating and verifying them.
  - JWT tokens can store user data in them. We will put email data for later use on verifications.
  - I will have a token generator function. Which, given an email, secret and expiry time, returns a JWT token.

- [x] Create `/refresh_tokens` endpoint.
  - Check if refresh token exists in our Db.
  - If so, decrypt and get the email.
  - Check if it belongs to same user.
  - Generate new tokens and return.
```jsx
// POST
refresh_tokens({
  'email': 'muhammet.sen@boun.edu.tr',
  'refresh_token': 'old_refresh_token'
}) -> 
{
  'message': 'Access and Refresh Tokens are Updated!',
  'access_token': 'new_access_token',
  'refresh_token': 'new_refresh_token',
}
```

- [x] Handle authorization middleware.
  - Take Authroziation bearer token from header.
  - Decrypt it, getting email.
  - Get user data from DB and check if the tokens match.
  - If so, put the user data to `req.auth`

- [x] Create `/logout` endpoint.
  - Using access token, get user data, provided from auth middleware.
  - Remove access and refresh tokens of the user.
```jsx
// POST
logout({

}) -> 
{
  'message': 'Logout is successful!',
}
```

### Deliverable(s)

* Pull requests and commits, related to these topics.

### Acceptance Criteria

* Pull request must be reviewed and merged to master.

### Deadline of the issue

25.10.2022 @23.59

**Comment by ersoykadir** [comment]
[Commits](https://github.com/bounswe/bounswe2022group3/pull/293/commits) and [PR](https://github.com/bounswe/bounswe2022group3/pull/293) can be seen.
