### ISSUE TITLE
Create Course and Enrollment related functions according to API specifications by front

### ISSUE THREAD

**Issue by furkanakkurt1335** [bounswe/bounswe2022group3#303]
### Issue

Frontend and mobile teams have collaborated to create [API specifications](https://github.com/bounswe/bounswe2022group3/issues/270) for the backend team to implement. I was assigned 3 functions specifically, also requiring me to also create database schemas for the relevant functions: `getCourses`, `getEnrolledCourses` and `getCourseDetail`.

These functions need to implemented.

### Task(s)

- [X] Create the `getCourses` [function](https://github.com/bounswe/bounswe2022group3/issues/270#issuecomment-1282260863)
- [X] Create the `getEnrolledCourses` [function](https://github.com/bounswe/bounswe2022group3/issues/270#issuecomment-1282260863)
- [X] Create the `getCourseDetail` [function](https://github.com/bounswe/bounswe2022group3/issues/270#issuecomment-1282260863)

### Deliverable(s)

* `app/server/src/routes/course/`
    - `course.controller.js`
    - `course.route.js`
    - `course.validate.js`
* `app/server/src/routes/enrollment/`
    - `enrollment.controller.js`
    - `enrollment.route.js`
    - `enrollment.validate.js`

### Acceptance Criteria

* `getCourses` function works as expected, provided below.
* `getEnrolledCourses` function works as expected, provided below.
* `getCourseDetail` function works as expected, provided below.

Expectations for these functions are:
- The functions return data as requested in #270, functionally.

### Deadline of the issue

21.10.2022 23:59

### Reviewer

Burak Yılmaz

### Deadline for Review

22.10.2022 17:00
