### ISSUE TITLE
Document Individual Reports for Customer Milestone 1

### ISSUE THREAD

**Issue by furkanakkurt1335** [bounswe/bounswe2022group3#304]
### Issue

We need to document our individual reports by Nov 1 for the customer milestone 1. We already have documented our weekly efforts, we just need to synthesize and condense them in this report.

### Task(s)

For each member, document your individual report:
- [x] Arif Akbaba
- [x] Berke Özdemir
- [x] Bilal Aytekin
- [x] Burak Yılmaz
- [x] Furkan Akkurt
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Mehmet Gökberk Arslan
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Nurlan Dadashov
- [x] Salim Kemal Tirit

### Deliverable(s)

* The wiki page of [Individual Reports](https://github.com/bounswe/bounswe2022group3/wiki/individual-reports-451)

### Acceptance Criteria

* All the members have documented their individual reports.

### Deadline of the issue

01.11.2022 12:00

### Reviewer

Furkan Akkurt

### Deadline for Review

02.11.2022 00:00

**Comment by ersoykadir** [comment]
### Kadir Ersoy
-  **Member**: Kadir Ersoy - 2018400252 - Group 3 - Backend Team
- **Responsibilities**: I have been assigned to work on register/login and authorization features of the backend.
- **Main contributions**: I have handled `/register`, `/login`, `/logout` endpoints and authorization middleware.
  - **Code related significant issues**: #302 
  - **Management related significant issues**: #268, #269 
- **Pull requests**: #293

**Comment by muhammetssen** [comment]
### Muhammet Şen
-  **Member**: Muhammet Şen - 2018400192 - Group 3 - Mobile Team
- **Responsibilities**: I have been assigned to initialize the mobile app project, design and implement homepage and search page.
- **Main contributions**: 
  - Initialized the Flutter project, BUcademy
  - Created a view - viewmodel - service structure to have consistincy between different team members 
  - Implemented homepage and search views
  - Established connection structure with our backend  
- **Code related significant issues**: #281, #295, #316
- **Management related significant issues**:  #276, #270
- **Pull requests**: #282, #296, #317
- **Additional information**: I have reviewed PRs of my team members

**Comment by berkeozdemir2016400246** [comment]
### Berke Özdemir
-  **Member**: Berke Özdemir - 2016400246 - Group 3 - Frontend Team
- **Responsibilities**: I have been assigned to work on home page, user page and search functionality for the web application.
- **Main contributions**: 
  - I have created the home component and user courses component.
  - I have implemented the navbar component to use in those pages.
  - I have implemented a course card component to use in those pages.
  
- **Code related significant issues**: #325 , #326 
- **Management related significant issues**: #276, #269.
- **Pull requests**: #324
- **Additional information**: I have helped the team with PR reviews.

**Comment by hsuleerkul** [comment]
### Hatice Şule Erkul
-  **Member**: Hatice Şule Erkul - 2017400051 - Group 3 - Mobile Team
- **Responsibilities**: I have been assigned to design and implement profile page.
- **Main contributions**: 
  - Implemented profile views
- **Code related significant issues**: [#327](https://github.com/bounswe/bounswe2022group3/issues/327)
- **Management related significant issues**:  [#263](https://github.com/bounswe/bounswe2022group3/issues/263) [#269](https://github.com/bounswe/bounswe2022group3/issues/269)
- **Pull requests**:
- **Additional information**: I have reviewed PRs of my team members

**Comment by mertcan-ozkan** [comment]
### Mertcan Özkan
-  **Member**: Mertcan Özkan - 2019400081- Group 3 - Frontend Team
- **Responsibilities**: I have been assigned to work on course summary page and a section in course detail page.
- **Main contributions**: 
  - I have implemented the course summary page.
  - I have implemented the topics grid and icons of the course details page, these were later incorparated into course details page by Nurlan. 
- **Code related significant issues**: #289 
- **Pull requests**: #286 
- **Additional information**: I have helped the team with PR reviews.

**Comment by arfakbaba** [comment]
### Arif Akbaba
-  **Member**: Arif Akbaba -2016400375- Group 3 - Frontend Team
- **Responsibilities**: I have been assigned to work on profilepage design and apply backend connection of profile page.
- **Main contributions**: I have reviewed a part of the requirements/designs. I have updated communication channel part according to group meetings. I have implemented profilepage and backend connection getuser() profile.
 - **Code related significant issues**:
  #305
  #313 
- **Pull requests**: #314
 -   **Additional information**: I have reviewed PRs of my team members

**Comment by Goko6** [comment]
### Mehmet Gökberk Arslan
-  **Member**: Mehmet Gökberk Arslan - 2018400240 - Group 3 - Backend Team
- **Responsibilities**: I have been assigned to work on user profile and personal info endpoints.
- **Main contributions**: 
  - I have reviewed a part of the requirements/designs and updated them. 
  - I have implemented a part of the `/user`  endpoint.
- **Code related significant issues**: #275 
- **Management related significant issues**: #330 
- **Pull requests**: #294 
- **Additional information**: I have helped the team with PR reviews.

**Comment by bilalcim** [comment]
### Bilal Aytekin
-  **Member**: Bilal Aytekin - 2018400132 - Group 3 - Mobile Team
- **Responsibilities**: I have been assigned to design and implement the login and registration pages.
- **Main contributions**: 
  - Implemented the login and registration views. 
- **Code-related significant issues**: [#307](https://github.com/bounswe/bounswe2022group3/pull/307)
- **Management-related significant issues**:  [#259](https://github.com/bounswe/bounswe2022group3/issue/259)
- **Pull requests**: [#307](https://github.com/bounswe/bounswe2022group3/pull/307)
- **Additional information**: I have reviewed the PRs of my team members.

**Comment by salimtirit** [comment]
### Salim Kemal Tirit
-  **Member**: Salim Kemal Tirit - 2019400153 - Group 3 - Mobile Team
- **Responsibilities**: I have been assigned to design and implement the course page.
- **Main contributions**: 
  -Implemented the course view. 
- **Code related significant issues**: [#306](https://github.com/bounswe/bounswe2022group3/issues/306), [#319](https://github.com/bounswe/bounswe2022group3/issues/319)
- **Management related significant issues**:  [#263](https://github.com/bounswe/bounswe2022group3/issues/263), [#269](https://github.com/bounswe/bounswe2022group3/issues/269)
- **Pull requests**: [#318](https://github.com/bounswe/bounswe2022group3/issues/318)
- **Additional information**: I have reviewed PRs of my team members

**Comment by nurlandadashov02** [comment]
### Nurlan Dadashov
-  **Member**: Nurlan Dadashov - 2019400300 - Group 3 - Frontend Team
- **Responsibilities**: I have been assigned to initialize the frontend project, design and implement registration, login, email confirmation, discussions, notes pages.
- **Main contributions**: 
  - Initialized the frontend project, BUcademy
  - Created an authentication layout for registration and login pages
  - Created main layout for learning space which contains resources, events, discussions, notes pages
- **Code related significant issues**: [#287](https://github.com/bounswe/bounswe2022group3/issues/287), [#311](https://github.com/bounswe/bounswe2022group3/issues/311), [#312](https://github.com/bounswe/bounswe2022group3/issues/312)
- **Management related significant issues**:  [#260](https://github.com/bounswe/bounswe2022group3/issues/260), [#270](https://github.com/bounswe/bounswe2022group3/issues/270)
- **Pull requests**: [#277](https://github.com/bounswe/bounswe2022group3/pull/277), [#309](https://github.com/bounswe/bounswe2022group3/pull/309), [#320](https://github.com/bounswe/bounswe2022group3/pull/320/)
- **Additional information**: I have reviewed PRs of my team members and have been coordinating work of Frontend team

**Comment by yilmaz-burak** [comment]
### Burak Yılmaz
-  **Member**: Burak Yılmaz - 2018400237 - Group 3 - Frontend Team
- **Responsibilities**: I have been assigned to initialize the backend project, design and implement chapter,content,discussion,comment,badge classes. Also, I helped deployment of the frontend project.
- **Main contributions**: 
  - Initialized the backend project
  - Created the following classes as mongodb schemas: chapter,content,discussion,comment,badge
  - Deploy frontend project
- **Code related significant issues**: [#274](https://github.com/bounswe/bounswe2022group3/issues/274)
- **Management related significant issues**: [#270](https://github.com/bounswe/bounswe2022group3/issues/270)
- **Pull requests**: [#291](https://github.com/bounswe/bounswe2022group3/pull/291), [#292](https://github.com/bounswe/bounswe2022group3/pull/292)
- **Additional information**: I have reviewed PRs of my team members and have been coordinating work of backend team. As a team, we did lots of pair programming and meetings.

**Comment by ersoykadir** [comment]
The individual reports are documented and visible [here](https://github.com/bounswe/bounswe2022group3/wiki/Individual-Reports-451). Also they are included in Milestone 1 report.
