### ISSUE TITLE
[Mobile] Course Page

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#306]
### Issue

BUcademy needs a course page (learning space ?). This will be the main page for a course. A user will be able to see the contents of a course, events, quizzes, and the discussion about the whole course. 

### Task(s)

- [x] Create a course page
   - [x] Add course image
   - [x] Add name of the course
   - [x] Add course description
   - [x] Add the score of the course
   - [x] Add the number of enrolled people
   - [x] Add chapters tab
   - [x] Add events tab
   - [x] Add quizzes tab
   - [x] Add discussion tab
- [x] Make the course page accessible from the homepage.

### Deliverable(s)

* Course page including all contents about the course in a structured manner. 

### Acceptance Criteria

* Being able to see the course content.

### Deadline of the issue

28.10.2022 @23.59

### Reviewer

Muhammet Şen

### Deadline for Review

29.10.2022 @23.59

**Comment by muhammetssen** [comment]
Closed by #318
