### ISSUE TITLE
Mobile - Backend Connection

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#316]
### Issue

We should have a well designed class structure to make it easier to send requests and get responses from our backend server.

### Task(s)

- [x] Create data classes
  - [x] Course
  - [x] User
- [x] Crete serialization and deserialization methods via [json_serializable](https://pub.dev/packages/json_serializable)
- [x] Create a service that encapsulates http library we will use, Dio. It should add autherization tokens before sending requests
- [x] Create a user service to handle login, registration, refresh tokens and email confirmation

### Acceptance Criteria

- Being able to consturct Course and User classes by parsing JSONs
- Being able to send login, register, email confirmation, and refresh token requests

### Deadline of the issue

29.10.2022 @23:59
