### ISSUE TITLE
Milestone 1 Group Report

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#322]
### Issue

We need to prepare our group report for Milestone 1. 
![image](https://user-images.githubusercontent.com/49765256/198852481-199f458b-8cf6-4a8e-9612-de524642aa73.png)
Everything except Group review needs to be done before Monday. Group review will be done after milestone presentation in Tuesday.

### Task(s)

- [x] Software Requirements Specification
- [x] Software Design (UML) (Just related links are okay)
- [x] Scenarios and Mockups 
- [x] Project Plan
- [x] Individual Contribution Reports
- [x] Customer Milestone 1 Group Review (AFTER PRESENTATION!!)
  - [x] 1. Executive Summary: Summary of the project status and any changes that are planned for
moving forward. 
  - [x] 2. List and status of deliverables. 
  - [x] 3. Evaluation of the status of deliverables and its impact on your project plan.
    - [x] Software Requirements Specification 
    - [x] Software Design (UML) 
    - [x] Scenarios and Mockups 
    - [x] Project Plan
    - [x] Individual Contribution Reports 
  - [x] 4. Evaluation of tools and processes you have used to manage your team project. 
  - [x] 5. The requirements addressed in this milestone. 
  - [x] 6. Overall description of responsibilities that are assigned to each member.
    - [x] Front-end
    - [x] Mobile
    - [x] Back-end
  - [x] 7. A Summary of work performed by each team member (in tabular format).

|Task|Assignee| Status |
|---|---|---|
| Executive Summary | @yilmaz-burak  | <ul><li>- [X] </li></ul> |
| List and status of deliverables. | @hsuleerkul  | <ul><li>- [X] </li></ul> |
| Evaluation of Software Requirements Specification| @bilalcim | <ul><li>- [X] </li></ul> |
| Evaluation of Software Design (UML) | @Goko6  | <ul><li>- [X] </li></ul> |
| Evaluation of  Scenarios and Mockups |@mertcan-ozkan | <ul><li>- [X] </li></ul> |
| Evaluation of  Project Plan | @ersoykadir | <ul><li>- [X] </li></ul> |
| Evaluation of Individual Contribution Reports | @arfakbaba  | <ul><li>- [X] </li></ul> |
| Evaluation of tools and processes | @salimtirit  | <ul><li>- [X] </li></ul> |
| The requirements addressed in this milestone | @berkeozdemir2016400246  | <ul><li>- [X] </li></ul> |
|  Overall description of responsibilities that are assigned to each member - Backend | @furkanakkurt1335 | <ul><li>- [x] </li></ul> |
|  Overall description of responsibilities that are assigned to each member - Frontend| @nurlandadashov02  | <ul><li>- [X] </li></ul> |
|  Overall description of responsibilities that are assigned to each member - Mobile| @muhammetssen | <ul><li>- [X] </li></ul> |

### Deliverable(s)

* Milestone 1 Group Report

### Acceptance Criteria

* All deliverables must be committed under the `/deliverables/CMPE451_Customer_Presentation_Milestone_1` repository.
* All deliverables must be documented appropriately within .md files.

### Deadline of the issue

04.11.2022 @18:00

**Comment by ersoykadir** [comment]
Customer Presentation Report for Milestone 1 is [here](https://github.com/bounswe/bounswe2022group3/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_1). Group review will be prepared and uploaded as well.

**Comment by ersoykadir** [comment]
## Evaluation of Project Plan
The project plan is based on the team and customer meetings about what should be accomplished until the first customer milestone, and estimations about the second and last milestones. An outline of the plan was talked in the [meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2318-16.10.2022) regarding what is necessary before starting the implementation, what should be implemented in which order and what may be the aim future milestones. So, after the decision making of the objectives for this milestone, the group got seperated into Backend, Frontend and Mobile teams and distributed their related tasks within each other. ([Backend](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%232-BackEnd-Team),[Front](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes--%231--Front-End-Team), [Mobile](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231-19.10.2022-Mobile-Team) meetings). Then, a draft of project plan is prepared from these meetings and presented to customer for confirmation. Project plan was finished with adjustments done due to the feedbacks from customer like adding the assignee's names for each task on the plan etc.([#268](https://github.com/bounswe/bounswe2022group3/issues/268))

**Comment by bilalcim** [comment]
## Evaluation of Software Requirements Specification

Last term, we compiled a list of requirements specifying all kinds of features of our software. When we started the implementation, we realized that we need to tweak the old list to get it up-to-date. You can see our reviews in Issue #258.

We went over the reviews in the [Week 1 Team Meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2316-11.10.2022) and each of us got a section from requirements and updated it accordingly: Issue #269.

As the demands of the customer got changed/clarified, we needed a change both in the design of the platform and the terminology we use to address the common structures in it. These were handled in Issue #330.

**Comment by Goko6** [comment]
## Evaluation of Software Design (UML)
We have fully completed our class, use-case and sequence diagrams last term for the [CMPE352 Milestone-1 deliverables](https://github.com/bounswe/bounswe2022group3/blob/master/deliverables/M1-Group-3-Deliverables.pdf). However, after receiving customer requests to modify our design we needed changes in these diagrams. We needed a lot of name changes in the app since in the customer meeting, the feedback we received said that the way classes in our app are named does not make our app look like a co-learning platform. 

We have updated the use-case diagram ([#329](https://github.com/bounswe/bounswe2022group3/issues/329)) according to the changes requested. As discussed in [group meeting 30.10.2022](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2319-30.10.2022), we will update the class diagram. However, we have not decided on how to update the sequence diagrams yet.

**Comment by mertcan-ozkan** [comment]
## Evaluation of Scenarios and Mockups
 Last term, we created three scenarios to show how our application would perform when users with different requests were to use it. These scenarios were created based on the the list of requirements created by the team in the last semester. After the creation of scenarios, two mockups  for each scenario was designed to show how our application would look like in frontend and mobile. 

 In this term we realized that some of the requirements created last term needed some modififaction and update to meet with customer requests. ([#269](https://github.com/bounswe/bounswe2022group3/issues/269)) After updating the requirements scenarios and mockups were also rewieved and updated again according to new requirements.([Scenario1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1), [Scenario2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2), [Scenario3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3))

 After the update, mobile and front-end teams started designing the corresponding pages shown in mockups. The general design structure  for the pages were kept but some design features were changed during the implementation process. For milestone 1, most of the pages shown in these scenarios are implemented except polling and event creation pages.

**Comment by muhammetssen** [comment]
## Overall description of responsibilities that are assigned to each member - Mobile
### Salim Kemal Tirit
**Implementing learning space details page**: Space details page contains all the information regarding a space, like description, resources, events, and quizzes. 
### Hatice Şule Erkul
**Implementing profile page**: Similar to space details page, profile page contains all the information regarding a user. Our platform has a lot of different sections that a user can fill, like interest and knowledge. Moreover, profile page also contains a user's activities, achievements, and spaces.
### Muhammet Şen
**Initializing the flutter project**: Providing a base structure to have consistency between developers, like creating a singleton service architechture.
**Implementing homepage and search pages***
### Bilal Aytekin
**Implementing login and registration pages**: Pages that contain forms that user can login and sign up to BUcademy.

**Comment by berkeozdemir2016400246** [comment]
Requirements Adressed in the Milestone:

For the milestone demonstration we had the following features ready:

<details>
  <summary><b>1.1 Account Features</b></summary>
  
* 1.1.1 Registration 	
    *  1.1.1.1. Users shall be able to register using a valid and unique email address, a username, and a password as defined in the security section.
        *  1.1.1.1.1.  Users who are registered by providing their emails shall confirm their accounts via the link sent in the confirmation email.
    *  1.1.1.2. Users shall be able to register using their Google account.
* 1.1.2 Log In
    * 1.1.2.1. Users shall be able to log into their account using their email and password combination.
    * 1.1.2.2. Users shall be able to log into their account using their Google account (if they have previously completed 1.1.1.2.).
    * 1.1.2.3.  If a user enters their password wrong three times while logging in their password will be invalidated. They will receive a warning email containing a link to reset their password.
    * 1.1.2.4. Users shall be able to reset their password via email verification.
* 1.1.3 Log Out
    * 1.1.3.1 Users shall be able to log out of their account.
</details>

<details>
  <summary><b>1.2. Profile</b></summary>
  
* 1.2.1. Users shall have their own profiles.
* 1.2.2. Users shall be able to use the features of their profile page. (described in 2.1.2.)
</details>

## System Requirements
<details>
  <summary><b>2.1. Profile Page</b></summary>

* 2.1.1. The system shall keep a profile page for every user registered that can also be edited by the user. (With mock data and as a rough draft)
</details>

<details>
  <summary><b>2.2. Communication Channel</b></summary>

* 2.2.1. The system shall provide an interface such that users can ask and answer questions. (With mock data and as a rough draft)
</details>

<details>
  <summary><b>2.3. Note Taking</b></summary>

- 2.3.1 The system shall provide a notes section in profile. (With mock data and as a rough draft)
</details>

**Comment by hsuleerkul** [comment]
## List and Status of Deliverables

| Deliverable | Name | Last Updated |
|---|---|---|
| [Software Requirements Specification](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) | Completed | 31.10.2022 |
| [Class Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams) | Completed | 31.10.2022? |
| [Use Case Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Use-Case-Diagrams) | Completed | 31.10.2022 |
| [Sequence Diagrams](https://github.com/bounswe/bounswe2022group3/wiki/Sequence-Diagrams) | Completed | 31.10.2022? |
| [Scenario and Mockup 1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1) | Completed | 31.10.2022 |
| [Scenario and Mockup 2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) | Completed | 31.10.2022 |
| [Scenario and Mockup 3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3) | Completed | 31.10.2022 |
| [Project Plan](https://github.com/bounswe/bounswe2022group3/wiki/Project-Plan) | Ongoing | 31.10.2022 |
| [Individual Contribution Reports](https://github.com/bounswe/bounswe2022group3/wiki/Individual-Reports-451) | Completed | 2.11.2022 |
| [Customer Milestone 1 Group Review](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Milestone-1-Feedbacks) | Completed | 3.11.2022 |

**Comment by furkanakkurt1335** [comment]
## Overall description of responsibilities that are assigned to each member - Back-end

Initially, all of the members of the back-end team were assigned with the task of deploying the practice-app of the previous semester locally. In the same meeting, all the members were also assigned the task of dockerizing the initial back-end server with MongoDB.

In a meeting on 20/10/2022, the members were assigned with different API endpoints requested by the front-end and mobile teams together. The team assigned multiple endpoints to each member, keeping the endpoints given to a member relevant to each other. Because the team also needed database schemas for these endpoints, the members were assigned with the tasks of implementing the schemas mostly corresponding to their endpoints.

Afterwards, in a meeting on 22/10/2022, the members were assigned with the task of creating pull requests (PR) of their local branches and reviewing each other's resultant PRs.

### Furkan Akkurt

Assigned database schemas to implement were `Course` and `Enrollment`. Assigned API endpoints were `createCourse`, `getCourses`, `createEnrollment`, `getEnrolledCourses` and `getCourseDetail`.

### Kadir Ersoy

Assigned database schemas to implement was `User`. Assigned API endpoints were `register`, `login`, `refresh_tokens`, `logout` and `confirmEmail`.

### Burak Yılmaz

Assigned database schemas to implement was `Chapter`. Assigned API endpoints were `createChapter`, `getChapterContent` and `confirmEmail`.

### Mehmet Gökberk Arslan

Assigned database schemas to implement were `Personal Info` and `Badge`. Assigned API endpoint was `updatePersonalInfo`, `getProfile`, `createBadge` and `getBadge`.

**Comment by arfakbaba** [comment]
## Evaluation of Individual Contribution Reports

Two new friends joined our project this term.(Furkan Akkurt and Berke Özdemir). Two of our friends from the last term also left (Bengisu Takkin and Ahmet Kudu). First of all, before we started coding our project, we reviewed the customer's wishes and arranged the requirements and diagrams according to the decisions we made in the meetings we held. At this stage, our newly joined friends learned about the project and quickly adapted to the project, and as a team we evaluated everyone's ideas. Then we were divided into 3 teams. 
- Backend team: The backend team created a backend project and did the necessary part of the work, and then provided the necessary APIs for the frontend and mobile team.

- Front-end team: Frontend team created a frontend project. The frontend team designed the necessary pages for milestone 1 and coded these pages.

- Mobile Team: Mobile team created a maile project. They prepared the necessary pages for the mobile version of our project and created a initial version of product with the data provided by the backend APIs . 

All our teammates supported the project and demonstrated their work by opening issues, opening pull requests and reviewing the opened pull request. Thanks everyone who contributed.

**Comment by nurlandadashov02** [comment]
## Overall description of responsibilities that are assigned to each member - Frontend

### Nurlan Dadashov
Initialized the frontend project using next.js. This gave other developers a solid structure to follow and ensured consistency. Have been assigned to develop user authentication in frontend (register, login, email confirmation pages, and access/refresh token handling). Also, have been assigned to develop main layout for learning space and basic versions of discussions and notes.

### Berke Özdemir
Have been assigned to work on the home page and search functionality for it, user's 'my spaces' page. Developed common layout for these pages

### Arif Akbaba
Have been assigned to work on user profile page.

### Mertcan Özkan
Have been assigned to work on summary page for a learning space and a resources section of the learning space.

**Comment by yilmaz-burak** [comment]
## Executive Summary
### Project Descriptions
This project is an online learning platform which can offer such environments independent of the location of
the teachers and learners. There are two types of users in our platform, one is an admin user and the other
type of user can be a lecturer and a learner depending on the course. Lecturer implies anyone who knows
something well and can teach it and learner is anyone who is interested in learning. This departs from the
classical educational course room context. In this platform, users can enroll in a learning experience where
they will utilize resources and solve problems. They can monitor their progress of the enrolled course. They
can create notes related to what they are learning and share notes with others. They can also connect
notes, annotate and tag them. The users can also create a course and decide its contents. We call owners
of courses "lecturers". Lecturers can organize in-person meetings by specifying locations, dates, duration,
and other relevant information using the platform. Lecturers can also create polls to help the learners to
contribute some decisions taken during the lecture. Polls can be in three options: anonymous mode,
multiple answers, and quiz mode. Lecturer can also have reputations based on the feedback gathered by
the learners as they learn. This platform provides users to create their own a profile that describes their
interest and their knowledge. Users be able to follow other users and be able to see the
activities/achievements of those they follow in this platform. This platform offers semantic searching,
browsing, and recommendations to offer a rich learning environment. The system of this platform makes
recommendations based on the learning experience. This platform supports Android, and Web so that it is
available on both mobile and the web. We also take into consideration ethical concerns while designing our
platform. Therefore, we follow the rules of KVKK and GDPR and the standards of W3C as a software project.

### Project Status
In the beginning of the term, we have created 3 teams, namely backend, frontend and mobile. Since then, we have done a lot of meetings, pair programmings even, and discussions. We worked asynchronously, enabling for better efficieny.
After all 3 teams assigned a person in their teams to come up with the initial structure, all the team mates started contributing effectively. We have gathered the API specifications with collaboration of mobile, frontend and backend teams, minimizing the overhead of unnecessary communication. Backend team also provided a Postman configuration and overall local deployment tips, making it easier to deploy on local and progress on code base quick and without friction.
Because of all this coordination and atomicity, we were able to present in our Milestone presentation, a solid workflow of how our system works, what the use cases could be. 
So far, we implemented registration & login systems, as well as overall discussion, note taking, learning place and resource gathering sections. Some of the data were mocked and statically put there, however they were successful in demonstrating what the system does and looks like.
Alongside the way, we listened to the customer and changed our requirements accordingly.

### Forward Plans
We have implemented the overall structure for backend, frontend and mobile. Until milestone 2, we will expand the functionalities of our systems, covering more of our requirements. Alongside of it, we want to automate some processes and maybe even create development environments for team members to safely work with. We also plan to host a domain with secure https connection enabled. Alongside this we will expand our test cases as well. Since we have established our teams and internal communication systems, we should be able to progress without much obstacles.

**Comment by salimtirit** [comment]
## Evaluation of tools and processes

### [Github](https://github.com/)
GitHub is the main platform we used in our project. Basically, we did everything and put everything on GitHub.  We used the code part of Github this semester. We have used the project part of GitHub to track the status of the issues. We made commits and created pull requests when we needed them. It helped us collaborate on the project. We documented our requirements, questions, communication plan, meeting notes, personal efforts, user scenarios and mockups, and UML diagrams on Github. In the meetings, after discussing the meeting agenda and deciding who will do what we wanted everyone to open a related issue for that task. We have used the issue system to track our progress. We created a better issue template to organize our issues better. It increased our collaboration since we could comment on issues. We have used the markdown feature of GitHub exclusively in our issues and wiki pages. We also used the sidebar of GitHub to keep our wiki page organized. We used [README](https://github.com/bounswe/bounswe2022group3/blob/master/README.md) to create a nice page to introduce ourselves and the project.

### [WhatsApp](https://www.whatsapp.com/)
This semester we did not use WhatsApp that much. We used WhatsApp to communicate instantly and discuss small things. Since we all are used to checking WhatsApp frequently it helped us communicate. WhatsApp is generally hard to track so we didn’t use it for very important subjects that need to be checked by all team members. Generally, when we needed help or were not sure about a subject we used WhatsApp. We also used it for general chit-chat from time to time.

### [Slack](https://slack.com/)
This semester we did not use slack that much. But our professor kept sending us informative documents and nice links through Slack. It is unfortunate that Slack decided to change its user terms in a way that is not possible for us to keep using it. We even lost some of our precious links or documents that were in Slack. 

### [Zoom](https://zoom.us/)
This semester we did not use zoom that much. It had a time limit and since it is only for online meetings it was creating an overhead. But we used it at the beginning of the semester a couple of times.

### [Discord](https://discord.com/)
We basically replaced WhatsApp, slack, and zoom. We had separate channels for every team and a general chat. We did our online meetings in discord usually. The quality of videos and sound is a little worse than zoom but it was easier to get into a voice channel than generating and clicking a zoom link. And also Discord is used in everyday life for most of us so it was easier to check like WhatsApp. 

### [VS Code Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf)
This is a tool that we have used during the preparation of this document. Since we all got used to the markdown feature of GitHub we decided that we can write this document in GitHub under relevant issues and then connect it in a single PDF file. This tool can embed links, create tables, show emphasis, and even create plantUML diagrams inside the pdf. It is very useful and can be used inside vs code. It can export in pdf, HTML, png, and jpeg formats.

### [Google Docs](https://docs.google.com/)
We used Google Docs when we needed to collaborate on something written. It is free to use and like the online version of MS office so everyone is used to using it. Since it stores documents in Google Drive it is hard to lose a document.

### [ProjectLibre](https://www.projectlibre.com/)
We used project libre to prepare our project plan. It is open-source, free software. It is a desktop application and it is stated that there will be a cloud version. Apparently, the cloud version is being waited for a long time. Since it is only available as a desktop application we could not efficiently work on it. It was not practical to share the screen on zoom and try to fill a table together. It is not stable on different operating systems. Some features work in windows, others in ubuntu, and others on macOS. It crashes from time to time so we had to start over four times. The user interface is not good. We didn’t like this program at all. It didn’t make our job easier than it is. This program should not be recommended to any user or any group in the future. We are very disappointed about this.

### [Lucid.app](https://lucid.app/)
We used the lucid app to draw our diagrams. It allows us to work together on the same document. For example in the class diagrams everybody created the given class in the same document then we ordered them together in a discord meeting. For the use case diagram, we reviewed it in a meeting. It shows who is doing changes currently in the document but it doesn't show the information from the past. It can be tiring to try to find the owner of a change. Other than that it provides a solid, collaborative environment with many beautiful options of shapes. It is easy to use, moving objects and connecting them with arrows is pretty easy.

**Comment by ersoykadir** [comment]
Each and every part of the milestone 1 report is documented and posted on [repo](https://github.com/bounswe/bounswe2022group3/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/Group3-Customer_Milestone_1_Group_Review.md). Applauding everyone for the effort.
