### ISSUE TITLE
Milestone 1 Presentation

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#323]
### Issue

We need to prepare a presentation and have a scenario to present on customer review.

### Task(s)

- [x] Prepare a scenario.
- [x] Prepare slides if needed.
- [x] Decide on who will present.
- [x] Might need a practice presentation on Monday night.

### Deliverable(s)

* Presentation + Scenario.

### Acceptance Criteria

* Presenation must be ready for Milestone.

### Deadline of the issue

01.11.2022 @23.59

**Comment by ersoykadir** [comment]
Presentators chosen to be @salimtirit and @nurlandadashov02. Both had prepared a scenario for the presentation with no slides, over the live demo of our platform. 
Side note: They have performed very well and gotten beautiful feedbacks from the customers.
