### ISSUE TITLE
[Mobile] Profile Page

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#327]
### Issue

I am responsible for implementing profile pages in mobile BUcademy app. In [this](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231-19.10.2022-Mobile-Team) meeting we decided the layout. 

### Task(s)

- [x] Implement title bar
- [x] Implement profile picture
- [x] Implement about me section
- [x] Implement knowledge, interest sections with tags
- [x] Implement activities tab
- [x] Implement achievements tab
- [x] Implement courses/spaces tab
- [x] Implement notes tab
- [x] Implement backend connection

### Deliverable(s)

* Working profile page

### Acceptance Criteria

* Profile page of a user.

### Deadline of the issue
15.11.2022
