### ISSUE TITLE
[Mobile] Login and Registration Pages

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#339]
### Issue

I am responsible for implementing the login and registration pages in the mobile BUcademy app. In [this](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231-19.10.2022-Mobile-Team) meeting we decided on the layout.

### Task(s)

- [x] Implement app logo bar
- [x] Implement name bar
- [x] Implement email bar
- [x] Implement password bar
- [x] Implement login page
- [x] Implement registration page

### Deliverable(s)

* `mobile/login`

### Acceptance Criteria

* Login and registration pages are in accordance with the app.

### Deadline of the issue

31.10.2022 @23.59

### Reviewer

Bilal Aytekin

### Deadline for Review

31.10.2022 @23.59
