### ISSUE TITLE
[mobile] - Adding Deep Links

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#344]
### Issue

Our mobile app must support deep linking, opening the app when user clicks a link to our domain https://bucademy.tk . This feature is essential for scenarios like clicking the link in the confirmation email.

### Task(s)

- [x] Researching deep linking in Flutter
- [x] Finding a library from pub.dev
- [x] Implementing with our domain, bucademy.tk

### Acceptance Criteria

- Clicking a link in our domain name to open the app
- Clicking to the confirmation email to send the confirm request to our backend

### Deadline of the issue

12.11.2022 23:59
