### ISSUE TITLE
User Schema update

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#351]
### Issue

We need to adjust user endpoint. User schema on database has sensitive user informations like password hashes and tokens. We must avoid returning them on api requests. So I think we can move all sensitive info to tokens schema, remove all of them from user schema and token object reference as well. In any case we need these data, we can get it by email.

### Task(s)

- [x] Remove password related fields, move them to tokens.
- [x] Update endpoints that use password informations
  - [x] Get password hashes from token schema

### Deliverable(s)

* PR for related updates.

### Acceptance Criteria

* User and Tokens schema is updated.
* All endpoints that uses user password is updated

### Deadline of the issue

10.11.2022 @23.59

**Comment by ersoykadir** [comment]
We need to provide users with an option for resending the confirmatin mail
- resendConfirmation endponint
  - get input as email, if that email exists in our db and hasn't confirmed yet, send the conf mail again. reset the conf key
