### ISSUE TITLE
[Backend] Small updates on Enrollment

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#365]
### Issue

I will make small adjustments on enrollment endpoints. They are related to ease of use.

### Task(s)

- [ ] Add a delete enrollment endpoint.
  - [x]  We should add a `status` field to enrollment model. It would show whether that enrollment is active or not.
  - [ ] In the case of disenrollment, we can just change the status to passive, to not lose any enrollment related data and let user reuse it again in the future.
- [ ] Make a check on create enrollment/ delete enrollment, whether given course_id exists in our db or not.
- [x] Add a regex search on getEnrolledCourses just like getCourses endpoint

### Deliverable(s)

* PR for related updates.

### Acceptance Criteria

* PR is reviewed and merged.

### Deadline of the issue

19.11.2022 @23.59

**Comment by ersoykadir** [comment]
I have gone over the necessary updates. We have to important PR's ongoing and these updates will be merged after them. It needs to be bug checked after other PRs before merging
