### ISSUE TITLE
[Mobile] Content Page

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#368]
### Issue

BUcademy needs a content page inside the learning space. This will be a page that can be accessible through the course page by clicking a tile containing the topic's name. Inside the topic page, there may be many contents included. 

### Task(s)

- [x] Create a topic page.
  - [x] Make icons on the course page clickable.
  - [x] Put icons for the types of content.
  - [x] Put contents clickable
- [x] Create content pages

### Deliverable(s)

* Content Page

### Acceptance Criteria

* Working content page that can be reached from the course page

### Deadline of the issue

21.11.2022 @23.59

### Deadline for Review

22.11.2022 @15.00
