### ISSUE TITLE
[Mobile] Creating Markdown Editor Widget

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#375]
### Issue

We need a component that can be used at every part of Bucademy app. We shall support markdown language in comments, discussions, resources, notes etc. Hence, we can use the same input component for all of those.

### Task(s)

- [ ] Finding a markdown package from [pub.dev](pub.dev)
- [ ] Exploring different use cases of the package
- [ ] Creating a component that should include
  - [ ] OnChange callbacks
  - [ ] Loading state variables
  - [ ] OnComplete callbacks

### Deliverable(s)

- MarkdownInput widget

### Acceptance Criteria

- Component shall be responsive to the screen size
- Component shall be easy to use at other pages
- Component shall support providing onChange and onComplete callbacks
- Component shall support providing a loading state to indicate user during loadings

### Deadline of the issue

25.11.2022 23:59
