### ISSUE TITLE
[Backend]: Total flow test

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#380]
### Issue

Since we had many updates on backend, I will do a full test to check if the flow is still working and the pieces of backend work properly well with each other.

### Task(s)

- [ ] Test the flow with Postman.
- [ ] Prepare a new postman config with tested endpoints.
- [ ] Update the api specs with new configuration and inform teammates.

### Deliverable(s)

* PR related to updates.
* New postman config.
* Updated API specifications.

### Acceptance Criteria

* Related PR is merged and deliverables done.

### Deadline of the issue

27.11.2022 @ 17:00
