### ISSUE TITLE
Redesign home page and my spaces pages

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#383]
### Issue

Home page and my spaces pages shall be improved visually. Furthermore, my spaces page shall be connected to backend.

### Task(s)

- [x] implement new design for home page
- [x] implement new design for my spaces page
- [x] connect my spaces page to backend

### Deliverable(s)

* frontend

### Acceptance Criteria

* team is satisfied with new design

### Deadline of the issue

28.10.2022 @23.59

### Reviewer

Berke Özdemir

### Deadline for Review

30.10.2022 @23.59
