### ISSUE TITLE
[Backend] Profile Page

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#396]
### Issue

I will adjust userProfile endpoint to have a compact profile editing mechanism and have profile system detailed.

### Task(s)

- [x] Add public-private profile checks for getProfile.
- [x] Add check for whether the requester and the profile owner matches, for getProfile
- [x] Add is_private edit to updateProfile
- [x] Add name-surname edit to updateProfile
- [x] Add upload profile image endpoint
- [x] Add enrollments and created_spaces lists to getProfile
- [x] Add followUser endpoint
  - [x] Add followers and followed users to getProfile.

### Deliverable(s)

* PR for updates

### Acceptance Criteria

* PR is merged

### Deadline of the issue

30.11.2022 @23.59
