### ISSUE TITLE
[Backend] Note Schema and Endpoint

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#397]
### Issue

We need note schema and endpoints for note creation and getting notes.

### Task(s)

- [x] Create note schema
 - [x] Body, title, space_id, createdAt
- [x] Create /note endpoint
  - [x] create note given body, title, space_id 
  - [x] get note given note id
  - [x] get list of notes for given space_id
- [ ] Add notes to getSpace

### Deliverable(s)

* PR for note endpoint

### Acceptance Criteria

* PR fis merged

### Deadline of the issue

30.11.2022 @23.59

**Comment by ersoykadir** [comment]
Can't have notes on getSpaces.
