### ISSUE TITLE
[Frontend]: Annotation

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#401]
### Issue

Adding annotations to resources page. Created annotation shall follow W3C standard. 

### Task(s)

- [x] Find library for annotations
- [x] implement aanotations on resource markdown
- [ ] connect to backend to write new annotations and fetch

### Deliverable(s)

* frontend code

### Acceptance Criteria

* Users can create annotations

### Deadline of the issue

05.12.2022

### Reviewer

Mertcan Özkan

### Deadline for Review

05.12.2022

**Comment by nurlandadashov02** [comment]
I will implement web annotations using https://www.npmjs.com/package/@recogito/recogito-js
