### ISSUE TITLE
[Mobile] Add Topic

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#402]
### Issue

There needs to be an option to add a new topic to a learning space. 

### Task(s)

- [x] Creating add topic button
- [x] Creating a page to add topic info
- [x] connecting to backend

### Deliverable(s)

* Add topic functionality.

### Acceptance Criteria

* Ability to add topic

### Deadline of the issue

03.12.2022 @23.59

### Reviewer

None

**Comment by salimtirit** [comment]
I have added add topic functionality to the app. I connected it to the backend and it works properly.
