### ISSUE TITLE
[Mobile] Add Resource

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#403]
### Issue

There needs to be a future to add resources to a topic. 

### Task(s)

- [x] Creating an add resource button.
- [x] Creating an add resource page
- [x] Connecting to the backend

### Deliverable(s)

* Add resource button and page.

### Acceptance Criteria

* Ability to add resources to a topic.

### Deadline of the issue

03.12.2022 @23.59

### Reviewer

None
