### ISSUE TITLE
[Mobile] Annotation

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#404]
### Issue

Annotation support for text resources should be implemented according to the W3C standards summerized [here](https://github.com/bounswe/bounswe2022group3/wiki/annotation).

### Task(s)

- [ ] Implement annotation for markdown resources.
- [ ] Implement annotation for markdown notes.
- [x] Backend connection to update annotations. 

### Deliverable(s)

* Code for annotation functionality in Mobile.

### Acceptance Criteria

* Must be implemented in accordence to the W3C Annotation Standards.  

### Deadline of the issue

06.12.2022

### Reviewer

Salim Tirit

**Comment by hsuleerkul** [comment]
As we were using markdown, I was not able to implement annotations on markdown text in flutter. In mobile/annotation branch you can view an example for standard text values (i will commit the example later in the day )
