### ISSUE TITLE
[Frontend] : Profie page improvements

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#411]
### Issue

According to team metings,  Public and private profile adjust in profile page. If user is adjust its profile private, other users see profile with limited informations. If user have public profile, other user see their profile and user's informations.
If user open own profile, user can edit own profile.

### Task(s)

- [x] Private profile implement
- [x] Public profile implement 
- [x] Backend connection to edit user's profile

### Deliverable(s)

* Frontend codes implemented

### Acceptance Criteria

* 2.1.1. The system shall keep a profile page for every user registered that can also be edited by the user.
* 2.1.3.2. The system shall allow a follower of a user to see the following features of a profile: achievements, monitoring, interests, knowledge, bio ,notes ,annotations and activities
* 2.1.4.1. Users shall be able to change their privacy settings. A user shall have a public or a private profile. (described in 3.3.6.)

### Deadline of the issue

06.12.2022

### Reviewer

None

**Comment by arfakbaba** [comment]
Profil page improvments done for M2.
