### ISSUE TITLE
Document Individual Reports for Milestone 2

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#420]
### Issue

We need to document our individual reports for Milestone 2. We already have documented our weekly efforts, we need to combine and condense them in this report.

### Task(s)

Each member is to document their individual report:
- [x] Arif Akbaba
- [x] Berke Özdemir
- [x] Bilal Aytekin
- [x] Burak Yılmaz
- [x] Furkan Akkurt
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Mehmet Gökberk Arslan
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Nurlan Dadashov
- [x] Salim Kemal Tirit

### Template
Your individual milestone should be structured as follows:
- `Member`: Info about myself (name, group), Subgroup if applicable (such as backend, frontend,
android)
- `Responsibilities` : Overall description of the responsibilities that are assigned to me
- `Main contributions` : Overall description of my contributions to the project until Customer Milestone
Presentation
  - `Code related significant issues` : My issues that contribute to the code base demonstrated
during the demo
  - `Management related significant issues` : My issues that contribute to the management of our
software project
  - Note that only the most-significant ones, we track all your issues separately.
- `Pull requests` : My pull requests
- `Unit Tests` : All unit tests that you have personally written for your project since the beginning of the
project.
- `Additional information` : Further relevant information related to my contributions (optional)

### Deliverable(s)

* The wiki page of [Milestone 2 - Individual Reports](https://github.com/bounswe/bounswe2022group3/wiki/Milestone-2-Individual-Reports).

### Acceptance Criteria

* All the members have documented their reports.

### Deadline of the issue

~~05.12.2022 @23.59~~ (adjourned by lecturer) 09.12.2022 @15.00

### Reviewer

Bilal Aytekin

### Deadline for Review

~~06.12.2022 @13.00~~ (adjourned by lecturer) 09.12.2022 @17.00

**Comment by ersoykadir** [comment]
### Kadir Ersoy
-  `Member` : Kadir Ersoy - 2018400252 - Group 3 - Backend Team
- `Responsibilities` : I have been assigned to work on note endpoint, building test infrastructure and maintaining the current backend with bug fixing and doing necessary updates according to the requests of front and mobile team.
- `Main contributions` : 
  - I have implemented `/note` endpoint and updated /userProfile.
  - I have set up test infrastructure for backend.
  - I have helped resolving bugs and issues of backend that has come up during `backend - front/mobile` connection. 
- **Code related significant issues**: [#378](https://github.com/bounswe/bounswe2022group3/issues/378) [#389] [#397]
- **Management related significant issues**: [#342] [#346] [#437]
- **Pull requests**: [#364] [#371] [#384] [#386] [#392] [#398] [#406] [#409]
- **Additional information**: I have helped the team with PR reviews.

**Comment by mertcan-ozkan** [comment]
### Mertcan Özkan
-  `Member` :Mertcan Özkan - Group 3 - FrontEndTeam
- `Responsibilities` : I was tasked to create a new discussions component based on Nurlans previous code and adding it to the resource page, create new pop up component for adding discussions, editing notes, adding notes. Also creataing a discussions table for viewing all the discussions for a learning space, create a new notes component based on Nurlans previous code and connecting all these components and files to backend.
- `Main contributions` : I created the following: CreateDiscussions.jsx, EditNotes.jsx, CreateNote.jsx, PopModule.scss, Note.jsx, Discussions.js. Also edited Notes.js and [discussion_id].js . Connected newly created ones to backend.
 - `Code related significant issues` :
 -  [##416 ](https://github.com/bounswe/bounswe2022group3/issues/#416 ) 
 - [##415 ](https://github.com/bounswe/bounswe2022group3/issues/415)
 -  [#356](https://github.com/bounswe/bounswe2022group3/issues/356) 
- `Pull requests` : 
- [#355](https://github.com/bounswe/bounswe2022group3/pull/355)
-  [#428](https://github.com/bounswe/bounswe2022group3/pull/428) 
- `Additional information` : I have helped the team with PR reviews.

**Comment by bilalcim** [comment]
### Bilal Aytekin
-  `Member`: Bilal Aytekin - 2018400132 - Group 3 - Mobile Team
- `Responsibilities`: I have been assigned to work on the mobile application's login, registration, and event features.
- `Main contributions`: I have implemented the login and registration pages and connected them to the backend. I have implemented creating and viewing an event for the mobile application.
  - `Code related significant issues`: [#343](https://github.com/bounswe/bounswe2022group3/issues/343),  [#419](https://github.com/bounswe/bounswe2022group3/issues/419)
  - `Management related significant issues`: [#408](https://github.com/bounswe/bounswe2022group3/issues/408), [#420](https://github.com/bounswe/bounswe2022group3/issues/420)
- `Pull requests`: [#377](https://github.com/bounswe/bounswe2022group3/pull/377) [#433](https://github.com/bounswe/bounswe2022group3/pull/433)
- `Additional information`: I have helped the team with PR reviews.

**Comment by berkeozdemir2016400246** [comment]
### Berke Özdemir
-  `Member`: Berke Özdemir - 2016400246 - Group 3 - Frontend Team
- `Responsibilities`: I have been assigned to work on the web application's gdpr compliance, topic creation, resource creation, resource editing, resource displaying, space page refinement and event features. Reviewing teammates' codes.
- `Main contributions`: I have implemented the resource display, event and creation pages and connected them to the backend. I have implemented topic creation and resources list display for the resources pages. I have improved UI of the space page.
  - `Code related significant issues`: [#418](https://github.com/bounswe/bounswe2022group3/issues/418),  [#394](https://github.com/bounswe/bounswe2022group3/issues/394),  [#360](https://github.com/bounswe/bounswe2022group3/issues/360),  [#361](https://github.com/bounswe/bounswe2022group3/issues/361)
  - `Management related significant issues`:  [#420](https://github.com/bounswe/bounswe2022group3/issues/420)
- `Pull requests`: [#362](https://github.com/bounswe/bounswe2022group3/pull/362) [#434](https://github.com/bounswe/bounswe2022group3/pull/434) [#399](https://github.com/bounswe/bounswe2022group3/pull/399) [#395](https://github.com/bounswe/bounswe2022group3/pull/395) 
- `Additional information`: I have helped the team with PR reviews.

**Comment by Goko6** [comment]
### Mehmet Gökberk Arslan
-  `Member`: Mehmet Gökberk Arslan - 2018400240 - Group 3 - Backend Team
- `Responsibilities`: I have been assigned to work on profile endpoint and also configuring ratings for different schemas.
- `Main contributions`: I have implemented a part of the user profile page and I have modified the corresponding endpoints such that ratings can be set and read.
  - `Code related significant issues`: [#421](https://github.com/bounswe/bounswe2022group3/issues/421)
- `Pull requests`: [#423](https://github.com/bounswe/bounswe2022group3/pull/423) 
- `Additional information`: I have helped the team with PR reviews.

**Comment by nurlandadashov02** [comment]
### Nurlan Dadashov
-  `Member`: Nurlan Dadashov - 2019400300 - Group 3 - Frontend Team
- `Responsibilities`: I have been coordinating work of the frontend team. I have been communicating with backend and mobile teams and wrote backend specifications. I have been reviewing codes of other team members.
- `Main contributions`: I have implemented new design on the home and my spaces pages. I worked on implementing annotations for resources. I made styling corrections to many pages to make them visually more appealing.
  - `Code related significant issues` : [#383](https://github.com/bounswe/bounswe2022group3/issues/383) [#401](https://github.com/bounswe/bounswe2022group3/issues/401) [#417](https://github.com/bounswe/bounswe2022group3/issues/417)
  - `Management related significant issues` : [#352](https://github.com/bounswe/bounswe2022group3/issues/352) 
- `Pull requests` : [#407](https://github.com/bounswe/bounswe2022group3/pull/407),  [#390](https://github.com/bounswe/bounswe2022group3/pull/390)

**Comment by salimtirit** [comment]
### Salim Kemal Tirit
- `Member` : Salim Kemal Tirit - 2019400153 - Group 3 - Mobile Team
- `Responsibilities`:  I worked on the topics page and details of the topics on the mobile application. This includes viewing, editing, and deleting both content and topics.   
- `Main contributions`: I implemented the topic page. I implemented create and delete topic functionality. I implemented the resource page. I implemented creating, editing, and deleting resource functionalities. I implemented a nice pop-up type interface for showing options when the user clicks and holds onto topic or resource tiles. 
  - `Code related significant issues` : [#368](https://github.com/bounswe/bounswe2022group3/issues/368) [#402](https://github.com/bounswe/bounswe2022group3/issues/402) [#403](https://github.com/bounswe/bounswe2022group3/issues/403)  [#425](https://github.com/bounswe/bounswe2022group3/issues/425)  [#426](https://github.com/bounswe/bounswe2022group3/issues/426) 
  - `Management related significant issues` : [#347](https://github.com/bounswe/bounswe2022group3/issues/347) [#350](https://github.com/bounswe/bounswe2022group3/issues/350) [#438](https://github.com/bounswe/bounswe2022group3/issues/438)
- `Pull requests` : [#427](https://github.com/bounswe/bounswe2022group3/pull/427) [#436](https://github.com/bounswe/bounswe2022group3/pull/436)
- `Additional information`: I helped the team with PR reviews. I presented the mobile application part in the milestone presentations. I populated the database by creating new resources, discussions, topics, and notes.

**Comment by muhammetssen** [comment]
### Muhammet Şen
-  `Member`: Muhammet Şen - 2018400192 - Group 3 - Mobile Team
- `Responsibilities`:  I have worked on mobile app's notes and discussions parts. Moreover, I was responsible for initializing our domains (bucademy.tk and api.bucademy.tk) and getting ssl certificates.
- `Main contributions`: I implemented markdown editor component that we use across our mobile app. I created discussion page where user can post new discussions and view other discussions. Similarly, I implemented note taking page. Finally, I have implemented deep links to let users open the app by clicking a `bucademy.tk` url.
  - `Code related significant issues` : [#344](https://github.com/bounswe/bounswe2022group3/issues/344), [#391](https://github.com/bounswe/bounswe2022group3/issues/391), [#400](https://github.com/bounswe/bounswe2022group3/issues/400), [#430](https://github.com/bounswe/bounswe2022group3/issues/430), 
  - `Management related significant issues` : [#334](https://github.com/bounswe/bounswe2022group3/issues/334), 
- `Pull requests` : [#345](https://github.com/bounswe/bounswe2022group3/pull/345), [#376](https://github.com/bounswe/bounswe2022group3/pull/376), [#387](https://github.com/bounswe/bounswe2022group3/pull/387), 
[#431](https://github.com/bounswe/bounswe2022group3/pull/431),

**Comment by furkanakkurt1335** [comment]
## Furkan Akkurt

1. Member: My name is Salih Furkan Akkurt. I'm from Group 3.
2. Responsibilities: I was given the responsibility of creating a database schema and API functions for annotations compliant with the W3C standard for Web Annotation Data Model.
3. Main contributions: I have attended many meetings with the entire team present, only the back-end team and with the customer. I have contributed to the wiki of the project, creating and organizing management pages. I have created issues related specifically to me or to the entire team. For the back-end, I have created and maintained many API functions, requested by the web front-end and mobile teams. I have created the back-end for annotations, complying with the W3C standard for Web Annotation Data Model. I have reviewed many pull requests and merged them. I have updated many of the naming conventions (e.g. course -> space) on the back-end.
    - Code related significant issues: [#381](https://github.com/bounswe/bounswe2022group3/issues/381)
    - Management related significant issues: [#373](https://github.com/bounswe/bounswe2022group3/issues/373)
4. Pull requests: [#372](https://github.com/bounswe/bounswe2022group3/pull/372), [#374](https://github.com/bounswe/bounswe2022group3/pull/374), [#379](https://github.com/bounswe/bounswe2022group3/pull/379), [#382](https://github.com/bounswe/bounswe2022group3/pull/382), [#405](https://github.com/bounswe/bounswe2022group3/pull/405), [#410](https://github.com/bounswe/bounswe2022group3/pull/410), [#413](https://github.com/bounswe/bounswe2022group3/pull/413)
5. Unit tests: [396c1](https://github.com/bounswe/bounswe2022group3/commit/396c1d676f924cc2d13bfb74a9d700b2729a38a3)

**Comment by yilmaz-burak** [comment]
### Burak Yilmaz
-  `Member` : Burak Yilmaz - 2018400237 - Group 3 - Backend Team
- `Responsibilities` : Event and participation logic, occasional bug fixes and updates regarding the requests from mobile and frontend teams on backend server. Also, making sure that server runs in a robust and reliable way.
- `Main contributions` : I have implemented `event` endpoint and. Created auto-restart logic for the backend server.
  - `Code related significant issues` : [#385](https://github.com/bounswe/bounswe2022group3/pull/385) [#422](https://github.com/bounswe/bounswe2022group3/pull/422)
  - `Management related significant issues` : [#424](https://github.com/bounswe/bounswe2022group3/issues/424)
- `Pull requests` : [#385](https://github.com/bounswe/bounswe2022group3/pull/385) [#422](https://github.com/bounswe/bounswe2022group3/pull/422) 
- `Additional information` : I have helped the team with PR reviews. Also made sure that both frontend and backend deployments worked reliably by optimizing dependencies and monitoring load.

**Comment by arfakbaba** [comment]
### Arif Akbaba
-  `Member` :Arif Akbaba- Group 3 - FrontEndTeam
- `Responsibilities` : I was tasked to implement a new profile specifications. Accordingto team meeting, Profilepage implemented as public profile page, private profile page  and owner profile page that editible owner user.According to the code reviews of my teammates, I provided the necessary arrangements on these pages.
- `Main contributions` : I have implemented the following: [user_id].js .  I have implement public profile page private profile page  and connect to update profile page and rearranged get profile connections based on backend changes.
 - `Code related significant issues` : [#411](https://github.com/bounswe/bounswe2022group3/issues/411) 
 - `Management related significant issues` : [#439](https://github.com/bounswe/bounswe2022group3/issues/439)
- `Pull requests` :  [#412](https://github.com/bounswe/bounswe2022group3/pull/412)
- `Additional information` : I have helped the team with PR reviews.

**Comment by hsuleerkul** [comment]
### Hatice Şule Erkul
-  `Member`: Hatice Şule Erkul - 2017400051 - Group 3 - Mobile Team
- `Responsibilities`:  I was responsible for profile page and annotations of the mobile application.
- `Main contributions`: I wrote API specifications for profiles and created `.../classes/profile.dart` to connect profile pages to the backend. I implemented custom selection toolbar for annotations that is only available at `mobile/anotations` branch.
  - `Code related significant issues` : [#327](https://github.com/bounswe/bounswe2022group3/issues/327), [#404](https://github.com/bounswe/bounswe2022group3/issues/404)
  - `Management related significant issues` : [#363](https://github.com/bounswe/bounswe2022group3/issues/363)
- `Pull requests` : [#338](https://github.com/bounswe/bounswe2022group3/pull/338)
- `Additional Information` : I have reviewed following PR's :   [#345](https://github.com/bounswe/bounswe2022group3/pull/345), [#376](https://github.com/bounswe/bounswe2022group3/pull/376), [#427](https://github.com/bounswe/bounswe2022group3/pull/427)

**Comment by bilalcim** [comment]
Thank you, all! I have combined them under [Milestone 2 - Individual Reports](https://github.com/bounswe/bounswe2022group3/wiki/Milestone-2-Individual-Reports).

**Comment by ersoykadir** [comment]
Nicely done!
