### ISSUE TITLE
[Mobile] Edit Resource

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#426]
### Issue

There needs to be a future to edit resources.

### Task(s)

- [x]  Creating an edit resource button.
- [x]  Creating an edit resource page
- [x]  Connecting to the backend 

### Deliverable(s)

* Edit button and edit page

### Acceptance Criteria

* Being able to edit resources

### Deadline of the issue

05.12.2022 @23.59

### Reviewer

None
