### ISSUE TITLE
Milestone 2 Group Report

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#437]
### Issue

We need to prepare our group report for Milestone 2.
![image](https://user-images.githubusercontent.com/49765256/206511536-0921db18-b52a-4153-b84c-38fdd33bd9f7.png)

### Task(s)

- [x] Customer Milestone 2 Group Report 
  - [x] 1. Executive Summary: 
    - [x] Provide a summary of your project status
    - [x] Describe any changes your team has made or planned since Milestone 1 to improve
development process, explain how those changes will impact your process
    - [x] Describe the improvements you have planned for the remainder of your project
  - [x] 2. Progress based on teamwork
    - [x] A Summary of work performed by each team member (in tabular format). 
    - [x] Status of the deliverables of Milestone 2
      - Explain the changes you have made in Milestone 1 deliverables if you have made any
    - [x] Progress according to requirements
      - Provide progress according to requirements, being either not started, in progress, or
completed.
    - [x] API Endpoints
      - The API documentation
      - Link to the API
      - Three examples of API calls corresponding to core functionality of your application,
with instructions to access the functionality (you may share Postman collections)
    - [x] User Interface / User Experience
      - For each user interface design, provide links to the code in the project repository
      - Screenshots of all implemented Web and Mobile interfaces
    - [x] Annotations
      - Describe the status of annotations in your project
      - Provide your plans for implementing all functionalities associated with annotations.
    - [x] Standards
      - Explain the work you have completed towards the application of the W3C standards
and ontologies.
  - [x] 3.  Individual Reports
    - should be sorted alphabetically according to the surnames of team members.
    -  covering only the period between Milestone 1 and Milestone 2
    - #420 
 
|Task|Assignee| Status |
|---|---|---|
| Provide a summary of your project status | @yilmaz-burak   | <ul><li>- [x] </li></ul> |
| Describe any changes your team has made or planned since Milestone 1 | @berkeozdemir2016400246  | <ul><li>- [x] </li></ul> |
| Describe the improvements you have planned for the remainder of your project |  @muhammetssen | <ul><li>- [x] </li></ul> |
| Status of the deliverables of Milestone 2 | @bilalcim  | <ul><li>- [x] </li></ul> |
| Progress according to requirements | @mertcan-ozkan | <ul><li>- [x] </li></ul> |
| API Endpoints | @ersoykadir | <ul><li>- [x] </li></ul> |
| User Interface / User Experience - Front | @arfakbaba  | <ul><li>- [x] </li></ul> |
| User Interface / User Experience - Front | @nurlandadashov02   | <ul><li>- [x] </li></ul> |
| User Interface / User Experience - Mobile | @salimtirit   | <ul><li>- [x] </li></ul> |
| User Interface / User Experience - Mobile | @hsuleerkul  | <ul><li>- [x] </li></ul> |
|  Annotations | @furkanakkurt1335  | <ul><li>- [x] </li></ul> |
|  Standards | @Goko6  | <ul><li>- [x] </li></ul> |

### Deliverable(s)

* Milestone 2 Group Report

### Acceptance Criteria

* All deliverables must be committed under the `/deliverables/CMPE451_Customer_Presentation_Milestone_2` repository.
* All deliverables must be documented appropriately within .md files.

### Deadline of the issue

09.12.2022 @ 12.00

### Reviewer

None

**Comment by mertcan-ozkan** [comment]
# 451-temp

|Requirement | Status |
|---|---|
| ## User Requirements |  |
| 1.1 Account Features |  |
| -- 1.1.1 Registration|  |
| 1.1.1.1 | completed  |
| 1.1.1.1.1. |  completed |
| 1.1.1.2. | not started |
| -- 1.1.2 Log In  |  |
| 1.1.2.1. | completed |
| 1.1.2.2. | not started |
| 1.1.2.3. | not started |
| 1.1.2.4. | not started |
| 1.1.2.4. | not started |
| -- 1.1.3 Log Out |  |
| 1.1.3.1  | completed  |
| -- 1.2. Profile  |  |
|  1.2.1. | completed |
| 1.2.2.  | in progress |
| -- 1.3. User Actions |  |
| 1.3.1  | not_started |
| 1.3.1.1 | not_started |
| 1.3.2. | not started |
| 1.3.3.  | completed |
| 1.3.3.1. | completed |
| 1.3.3.2. | completed |
| 1.3.4.1. | completed |
| 1.3.4.2. | completed |
| 1.3.4.3. | completed |
| 1.3.4.3.1. | not_started |
| 1.3.4.3.1. | not_started |
| 1.3.4.4 | completed  |
| 1.3.4.5  | in_progress |
| 1.3.4.6 | not_started |
| 1.3.5  | in_progress |
| 1.3.6 (with its subtopics)| completed |
| 1.3.7 | completed |
| 1.3.8 (with its subtopics) |completed(expect 1.3.8.1 in_progress)  |
| 1.3.9 | not_started |
| 1.3.10 | not_started |
| 1.3.11 | completed |
| 1.3.12  | completed |
| 1.3.13 | completed |
| 1.3.14 | completed |
| 1.3.15. (with its subtopics) | completed |
| -- 1.4. Admin User (with its subtopics)  | not_started |
| ## System Requirements |  |
| -- 2.1. Profile Page |  |
| 2.1.2.1. Bio| completed |
| 2.1.1 | completed |
| 2.1.2.2. Achievements (with its subsections) | not started |
| 2.1.2.3. Interests (with its subsections) | completed |
| 2.1.2.2. Activities (with its subsections) | not started |
| 2.1.2.5. Monitoring (with its subsections) | not started |
| 2.1.2.6. Knowledge (with its subsections) | completed |
| 2.1.2.7. Rating (with its subsections) | not started |
| 2.1.2.8. Notes (with its subsections) | in progress |
| 2.1.3. Following (with its subsections) | in progress |
| 2.1.4. Privacy (with its subsections)| not started|
| -- 2.2. Communication Channel |  |
| 2.2.1 | completed |
| 2.2.2 | completed |
| 2.2.2.1 | not_started |
| 2.2.3 | not_started |
| -- 2.3. Note Taking |  |
| 2.3.1  | completed |
| 2.3.2  | not_started |
| 2.3.3   |not_started  |
| -- 2.4. Recommendations |
|2.4.1. |completed|
|2.4.1.1. |in progress|
| -- 2.5. Search Engine |  
|2.5.1.|completed|
|2.5.2.|completed|
|2.5.3. |in progress|
|2.5.4.|in progress|
|2.5.5. |not_started|
|2.5.6. |not_started|
|2.5.7.  (with its subtopics)|in progress|
| -- 2.6. Annotation | | 
|2.6.1|in progress|
|2.6.1.1|completed|
|2.6.2|not_started|
|2.6.3|in progress|
|2.6.4|completed|
| -- 2.7. Notifications(with its subtopics)|not_started |
| ## Non-Functional Requirements||
| -- 3.1. Accessibility and Availability| completed |
| -- 3.2. Security (with its subtopics)|completed (expect 3.2.5 not_started ) |
| -- 3.3. Privacy(with its subtopics)|completed (expect 3.3.6[with its subtopics] not_started ) |
| -- 3.4. Performance and Reliability||
|3.4.1.| completed |
|3.4.2.|completed|
|3.4.3.|completed|
|3.4.4|in_progress|
|3.4.5|in_progress|
|3.4.6|completed|
| -- 3.5. Standards (with its subtopics)|completed|

**Comment by ersoykadir** [comment]
- BucademyAPI documentation can be viewed from [here](https://documenter.getpostman.com/view/20679271/2s8YzL2kTF).
- https://api.bucademy.tk
- You can access to the three example functionalities of BucademyAPI from this [postman collection](https://www.postman.com/gold-flare-216577/workspace/bucademyapi-examples/collection/20679271-d56f8dec-e9a1-4495-820f-3bf38b7adc94?action=share&creator=20679271). 
  - You must register to the platform using `[POST]/user/register`. Then you will get a confirmation email. You can follow the link on the email to confirm your account. Then you must login to the system via `[POST]/user/login`. 
  - For the three functionalities;
    - Newly registered accounts can view existing spaces by `[GET]/space/searchSpaces`. If a keyword was provided `[GET]/space/searchSpaces/keyword`, it will perform search among the spaces. 
    - Also users can enroll to a space by `[POST]/enrollment`, providing a space id, which can be acquired from `[GET]/space/searchSpaces`. and view their enrollment via `[GET]/enrollment/getEnrolledSpaces`. 
      - For the explained enrollment endpoints to work, user must provide access token, which is provided by `[POST]/user/login`.
      - So, acquire an access token from login and put it to Authorization tab as bearer token. You can also put the access token to the provided postman environment's access token variable.

**Comment by berkeozdemir2016400246** [comment]
Improvements:
 - We have employed a more active of use of our communications channel (Discord). This has allowed for us a more dynamic development process, quickly deciding on or changing api specifications or frontend/mobile product decisions.
 - We also employed a smaller group based approach. Features and endpoints were divided among a teams members in that teams weekly meetings, then during the developments process members of different teams implementing the same feature would discuss it among themselves for detailing and specifying the actual work that needs to be done. Finally, the final product would be shown to the whole team. Working in this way has allowed everyone to focus on their specific tasks and abstracting the rest of the project.
 - We have no plans to change the workflow described above as it has worked.
 - We plan to divide work more equally over time, we did most of the work near the deadline.
 - We plan to write better PR reviews as merging the PR's close to the deadline was stressful.

**Comment by furkanakkurt1335** [comment]
# Annotations

**Status**: We have implemented the database schema for text annotations. It's compliant with the W3C standard of Web Annotation Data Model. We have implemented API functions for text annotation creation, retrieval, update and deletion. We have implemented text annotations for our web front-end, leveraging [an annotation library](https://www.npmjs.com/package/@recogito/recogito-js).
**Plans**: We plan to provide text annotation functionalities on our mobile front-end.

**Comment by muhammetssen** [comment]
## Improvements planned for the remainder of project
### Follow system
We have not started working on follow mechanism and activities. Users shall be able to follow each other and see followed users' activities. Backend should store actions users do and provide endpoints to show those activities to other users. Front and mobile will list activites in the profile page. We should  discuss adding a discover or feed page to visualize followed users activities.
### Semantic search engine
Bucademy will support semantic search that will be used especially while searching spaces. This will be mostly backend teams' task since we already have a search UI in mobile and frontend apps.
### Recommendation system
Similar to search engine, backend team should provide endpoints that will recommend new spaces to users according to their interests and current spaces.
### Achievements and badges
We will integrate achievements and badges throughout Bucademy. We are not completed the design part yet, there is more to discuss and decide.
### Annotations
Our backend and frontend supports text based annotations and mobile will support it too. Moreover, we are planning to implement image annotation. Lastly, we should store annotations on a different database, as requested by the customer.
### Rating
As a part of the co-learning experience, users should be able to rate resources and comments. Our backend completed most of the requirements for this rating system. Adding related features to mobile and front apps is in our current sprint.
### Note Taking
Being able to create new notes in our mobile app is the only missing part of note taking.
### Events
Backend and frontend teams have implemented event system. We will have it in our mobile app. We have not tested it in detail.

**Comment by yilmaz-burak** [comment]
## Executive Summary - Summary of  Project Status

### Project Status
After the milestone 1, we have greatly expanded our features in all of the teams. We have integrated almost all of the endpoints to both mobile and frontend applications. We have completely removed all of the static data in those applications and populated our database so that it has much more realistic data. This way, we were able to showcase a realistic usecase in the milestone 2.

Specifically, we have implemented and/or advanced the following schemas and relevant operations in a fully working manner: `space`, `comment`, `discussion`, `event`, `resource` and `annotation`.

We also got a domain name, `bucademy.tk`, and configured necessary SSL certificates. That enabled the HTTPS connection, which resulted in a much better UX.

Both the backend and the frontend deployments seem to be still working reliably, haven't even crashed once (except for faulty logic) since the optimizations made for them.

We also implemented an auto-restart mechanism for the containers that failed for unhandled exceptions. That helped with the downtime and the wait time for frontend and mobile teams.

Overall the teams are able to communicate even more clearly and in an even more agile way.

**Comment by nurlandadashov02** [comment]
## User
-	Register
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/user/register.js

![image](https://user-images.githubusercontent.com/45170430/206675478-7a135a24-630b-4890-8aa9-1fcc87b2985d.png)
-	Login
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/user/login.js

![image](https://user-images.githubusercontent.com/45170430/206675577-5f611083-bc46-4dea-8479-755fa7fb8d83.png)
-	Profile
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/user/%5Buser_id%5D.js

![image](https://user-images.githubusercontent.com/45170430/206675752-580f7c0b-2ebe-4603-b95e-f27d9267077b.png)

-	Home
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/index.js

![image](https://user-images.githubusercontent.com/45170430/206675870-1318db19-f74d-409e-9361-f282658b438c.png)

-	Myspaces
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/user/my_spaces.js

![image](https://user-images.githubusercontent.com/45170430/206675927-d5e2d714-b1f0-4fe6-8ba3-eb86893b5f79.png)

## Space
-	Space
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/space/%5Bspace_id%5D.js

![image](https://user-images.githubusercontent.com/45170430/206676175-4fe6f120-276e-4850-aa04-8527365a7532.png)

-	CreateSpace
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/space/create_space.js

![image](https://user-images.githubusercontent.com/45170430/206676316-b6daf455-0510-43fd-abf7-b4d66c2fe3e6.png)

## my/spaces/[space_id]
-	Discussion
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/discussions.js

![image](https://user-images.githubusercontent.com/45170430/206676671-be2d5b49-8213-4236-a467-424a20d8da91.png)

-	Event 
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/events.js

![image](https://user-images.githubusercontent.com/45170430/206676611-2d7eff91-ba05-44fd-bb1b-cb03e018fdf2.png)

-	Notes
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/notes.js

![image](https://user-images.githubusercontent.com/45170430/206676558-b6a0f206-9c2d-4147-9bba-237bd0ee4079.png)

-	Resources
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/resources.js 

![image](https://user-images.githubusercontent.com/45170430/206676497-c8b4807e-b086-48fc-a1e0-0485024e3bca.png)


## my/spaces/[space_id]/resoruce
-	Create resource
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/resource/%5Bresource%5D.js
 
![image](https://user-images.githubusercontent.com/45170430/206676804-92c97362-ad87-420b-9f25-7066ca6e94c6.png)

-	Resource
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/resource/%5Bresource%5D.js

![image](https://user-images.githubusercontent.com/45170430/206677079-64babede-5335-4b12-9836-2c4ee6219abe.png)

## my/spaces[space_id]/discussion/[discussion_id]
•	Discussion
https://github.com/bounswe/bounswe2022group3/blob/master/app/client/pages/my/spaces/%5Bspace_id%5D/discussion/%5Bdiscussion_id%5D.js

![image](https://user-images.githubusercontent.com/45170430/206677284-64d45c60-5f5d-41a2-a6bd-7032f1efda39.png)

**Comment by bilalcim** [comment]
## List and Status of Deliverables

| Deliverable | Status | Last Updated |
|---|---|---|
| [Software Requirements Specification](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) | Completed | 04.12.2022 |
| [Class Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Class-Diagrams) | Completed | 04.112022 |
| [Use Case Diagram](https://github.com/bounswe/bounswe2022group3/wiki/Use-Case-Diagrams) | Completed | 31.10.2022 |
| [Sequence Diagrams](https://github.com/bounswe/bounswe2022group3/wiki/Sequence-Diagrams) | Completed | 15.04.2022 |
| [Scenario and Mockup 1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1) | Completed | 31.10.2022 |
| [Scenario and Mockup 2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) | Completed | 31.10.2022 |
| [Scenario and Mockup 3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3) | Completed | 31.10.2022 |
| [Project Plan](https://github.com/bounswe/bounswe2022group3/wiki/Project-Plan) | Ongoing | 31.10.2022 |
| [Individual Contribution Reports](https://github.com/bounswe/bounswe2022group3/wiki/Milestone-2-Individual-Reports) | Completed | 09.12.2022 |
| [Customer Milestone 2 Group Review](https://github.com/bounswe/bounswe2022group3/issues/437) | Ongoing | 09.12.2022 |

**Comment by Goko6** [comment]
## Standards
Our annotations fit the W3C standard of Web Annotation Data Model except the part that needs a seperate database. We plan to construct a new database that is for annotation purposes only which will make our annotations fully fit the W3C standards. For geolocation, we have used longitudes and latitudes in our endpoints which are used to show/set event locations on a map in order to fit the W3C standards.
