### ISSUE TITLE
Organising the wiki page

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#443]
### Issue

There are many pages that can not be reached from the wiki page directly. The wiki page needs to be organized.

### Task(s)

- [x] Organising wiki page
- [x] adding pages to the sidebar
- [x] some meeting notes have the wrong title. needs to be fixed

### Deliverable(s)

* Wiki page

### Acceptance Criteria

* Organised wiki page.

### Deadline of the issue

22.12.2022 @23.59

### Reviewer

None

**Comment by salimtirit** [comment]
I have checked every page in the wiki and in the sidebar. Everything is ok right now.
