### ISSUE TITLE
Tracing Weekly Efforts - Week #11

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#445]
### Issue

All the team members need to keep track of their weekly efforts. You can find the created page [here](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-11-Personal-Efforts)

### Task(s)

- [ ] Arif Akbaba
- [ ] Bilal Aytekin
- [ ] Mehmet Gökberk Arslan
- [ ] Furkan Akkurt
- [ ] Nurlan Dadashov
- [ ] Hatice Şule Erkul
- [ ] Kadir Ersoy
- [ ] Berke Özdemir
- [ ] Mertcan Özkan
- [ ] Muhammet Şen
- [ ] Salim Kemal Tirit
- [ ] Burak Yılmaz

### Deliverable(s)

* The [451 Week 11 Personal Efforts](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-11-Personal-Efforts) page.

### Acceptance Criteria

* Weekly effort of each team member must be documented.

### Deadline of the issue

28.12.2022 @15.00

### Reviewer

None

**Comment by salimtirit** [comment]
Thanks to all of my group members for completing the weekly efforts.
