### ISSUE TITLE
Annotation Microservice

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#448]
### Issue

We will separate our annotation service from our backend, setting it on a different machine and using a DB reserved only for annotations. This is done purely for the sake of complying with W3C annotation standards.

### Task(s)

- [ ] Create a small backend service
  - [ ] Provide get and set endpoints for annotation
- [ ] Connect it to its own DB

### Deliverable(s)

* PR for accomplishing stated tasks

### Acceptance Criteria

* Related PR is merged.

### Deadline of the issue

22.12.2022 @23.59

### Reviewer

None
