### ISSUE TITLE
[Backend]: Activities Schema 

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#450]
### Issue

We need to create activities logs for each user when
- In the case of these events happening: Create resource/topic/space/discussion/enrollment/event

So I will create an Activities schema to store these logs in DB. We will have a feed list for each user that stores the activities log of the users themselves and the other users. We will create activities log after any event. 
At the get feed endpoint, I will get a list of user+followed users. Then query activities collection to acquire activities that belong to the users in the list. The mongo has a query `$in`, which will be helpful for this case.
example: 
![image](https://user-images.githubusercontent.com/49765256/209137556-71ca309b-e46f-447e-a056-09cb51aa85f9.png)

### Task(s)

- [x] Create Activities Schema
- [x] Set body template of activities for each event(create resource, space...)
- [x] On creation endpoints, create an activity object
- [x] Create getFeed endpoint
  - [x] Get all activities of the user and his followed users

### Deliverable(s)

* PR for accomplishing stated tasks

### Acceptance Criteria

* Related PR is merged

### Deadline of the issue

22.12.2022 @23.59

### Reviewer

None
