### ISSUE TITLE
[Frontend] Implementing Follow User and Block User Features

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#451]
### Issue

According to the [front-end discussion](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%235-Front-End-Team) and the requirements, blocking and following features should be implemented in the profile page. Users shall be able to follow and block other users by clicking the corresponding buttons on the profile page of the user they want to block or follow.

### Task(s)

- [ ] Add block button to profile page. 
- [ ] Connect follow button to the backend.
- [ ] Connect block button to the backend.

### Deliverable(s)

* "Are you sure?" pop-up when the user wants to block another user.
* A new button to UI.
* Code for connecting block and follow to backend.

### Acceptance Criteria

* 2.1.3.1. The system shall keep records of user-profiles followed by the user.
* 2.1.3.2. The system shall allow a follower of a user to see the following features of a profile: achievements, monitoring, interests, knowledge, bio, notes, annotations, and activities.

### Deadline of the issue

26.12.2022

### Reviewer

None

### Deadline for Review

26.12.2022

**Comment by mertcan-ozkan** [comment]
After the team meeting, we have decided to not include blocking feature for this milestone but following will be implemented. I have decided to merge this issue with issue https://github.com/bounswe/bounswe2022group3/issues/453, you can follow the process from there. I am closing this one.
