### ISSUE TITLE
[Frontend] Implementing Note Sharing and Note Sorting/Filtering

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#452]
### Issue

According to the [front-end discussion](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%235-Front-End-Team) and the requirements, the notes.js file should be updated so that the user should be able to filter their notes according to the topic. Also, users shall be able to share notes with each other. There is already a share note button, but it is not functional.  Users will be able to share notes by clicking this button to copy the URL of the note sharing the URL of the note with other users. 

### Task(s)

- [ ] Write the functionality of the note-sharing button.
- [ ] Write a method to sort the notes.
- [ ] Connect them to the backend.

### Deliverable(s)

* ...

### Acceptance Criteria

* 2.3.2 The system shall support viewing notes of public and followed users on their profiles. Similarly, notes reached by shared links should be visible if only the sharing end is public or followed.
* 2.3.3 The system shall provide registered learners the ability to connect, annotate and tag notes.

### Deadline of the issue

26.12.2022

### Reviewer

None

### Deadline for Review

26.12.2022

**Comment by mertcan-ozkan** [comment]
After discussing with the frontend team, I have decided to filter notes in the following way:
- user will be able to filter their notes according to topic. 
- user will be able to filter their notes according to resource within that topic.

**Comment by mertcan-ozkan** [comment]
I have decided to change the default design of the page as well. Now, notes are shown in a grid. I think showing them in a categorized way is much more convenient since it would look more organized.

**Comment by mertcan-ozkan** [comment]
- This is how to updated page looks like. The notes come are shown in their own topic. Users will be able filter the topic that they want to see by pressing the button filters button at the top. Also they can filter the notes by resource in a topic by pressing the dots at the end of the topic headers. 

![image](https://user-images.githubusercontent.com/74208991/209655885-c325546f-537d-4d5c-b443-cff40659e94f.png)

**Comment by mertcan-ozkan** [comment]
- I hace finished the implementation of topic sorting. Now users can sort the topics in the following way:
- 
![image](https://user-images.githubusercontent.com/74208991/209656294-e82c2236-a37a-415d-ab2b-86523f17458c.png)

**Comment by mertcan-ozkan** [comment]
- I hace finished the implementation of sorting resources. Now users can sort the notes in a resource in the following way:
- ![image](https://user-images.githubusercontent.com/74208991/209656463-892c5b17-3879-4c57-818d-3a6e1ef970af.png)
- In this example, I have first chosen a topic by filtering out other topic. Then I fitered all the resources other than what is shown in the example. But it is also possible to select several topics and select several resources in these topics too. Like in the following:
- ![image](https://user-images.githubusercontent.com/74208991/209656695-7184faf2-faf0-46f2-9ab1-74da365cd8ff.png)

**Comment by mertcan-ozkan** [comment]
- Lastly I have implemented copy to clipboard functionality too. Now users will be able copy the url of each note and share them with each other. By clinking the copy to clipboard button.(The third one)
- 
![image](https://user-images.githubusercontent.com/74208991/209656881-f0ea9a2f-2f5d-4835-be0a-4a4c0bc80cc6.png)

**Comment by mertcan-ozkan** [comment]
I have create two pull requests for this issue you can check them here:
- https://github.com/bounswe/bounswe2022group3/pull/461
- https://github.com/bounswe/bounswe2022group3/pull/488

**Comment by mertcan-ozkan** [comment]
After the reviews and fixes , the pull request are merged succesfully. I am closing this issue.
