### ISSUE TITLE
[Frontend] Updating interests and knowledge fields of profile page. 

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#453]
### Issue

According to the [front end discussion](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%235-Front-End-Team) and the requirements, users shall be able to determine their knowledge and interests fields in their profile page. This feature will be implemented by making the user choose from a predefined list of interests and knowledge. The knowledge and interests fields already exist, but they should be updated according to the description above and also connected to the backend.

### Task(s)

- [x] Update the knowledge field of the profile page.
- [x] Update the interests field of the profile page.
- [x] Add follow/unfollow button.
- [x] Connect them to the backend.

### Deliverable(s)

* Updated profile page.

### Acceptance Criteria

* 2.1.2.3.1. The system shall keep an interests section on the profile page.
* 2.1.2.3.2. The system shall keep a predefined list of the possible interests a user may have.
* 2.1.2.4.1. The system shall keep an activities section for each user.
* 2.1.2.4.2. The activities page shall be visible to the users that follow the owner of the profile page.

### Deadline of the issue

26.12.2022

### Reviewer

None

### Deadline for Review

26.12.2022

**Comment by mertcan-ozkan** [comment]
I have decided to merge the issue https://github.com/bounswe/bounswe2022group3/issues/451 with this one. So the functionality of follow will also be implemented here.

**Comment by mertcan-ozkan** [comment]
- I have completed the implementation of interest and knowledge tags. Now users are prompted to choose from a specific list of predefined interest and knowledge. It can be seen below.
- ![image](https://user-images.githubusercontent.com/74208991/209658523-4237108f-36a8-4b20-a432-010afc09361e.png)

**Comment by mertcan-ozkan** [comment]
- I have added the unfollow/follow button to profile page. It can be seen below:
-  ![image](https://user-images.githubusercontent.com/74208991/209658707-1a27c836-2d7c-4e4f-85b7-10fe519460b2.png)

**Comment by mertcan-ozkan** [comment]
- I have connected all the fetures to backend.The pull reqıest can be seen below:
- https://github.com/bounswe/bounswe2022group3/pull/463

**Comment by mertcan-ozkan** [comment]
After the reviews and fixes, the pull request is merged succesfully. I am closing this issue.
