### ISSUE TITLE
[Mobile] - Activities and Feed

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#474]
### Issue

One of the most important features of Bucademy of knowing what other learners are doing on the platform. Seeing activities in a dedicated feed page can increase the communication between users. Feed page will include activities for:
- Creating a new course
- Creating a new topic
- Creating a new resource
- Creating a new discussion 

### Task(s)

- [x] Create feed page
- [x] Create feed service
- [x] Implement Activity class
- [x] Get activities of user from backend
- [x] Redirect each activity to corresponding page

### Deliverable(s)

- Feed Page

### Acceptance Criteria

* User must be able to see activities of other users they follow
* User must be able to visit the space/topic/discussion seen in activities

### Deadline of the issue

26.12.2022 23:59

### Reviewer

None
