### ISSUE TITLE
[Mobile] - Edit Profile Page

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#481]
### Issue

A page for editing user's profile information is needed. It can be accessed by the editbutton on the right top corner of a user's profile page. 

### Task(s)

- [x] Implement button functionality for edit button.
- [x] Create a page for getting input from user. about their profile information. Included fields:  name, surname, bio,  isPrivate. 
- [x] Implement functionality for interest selection in edit page.
- [ ] Implement image uploading for profile picture.
- [x] Connect to the backend.

### Deliverable(s)

* An edit page for profile pages. 
* Functionality to upload images. 

### Acceptance Criteria

* User should be able to change / update their name, surname, bio, profile picture, profile visibility (isPrivate), and interests.

### Deadline of the issue

30.12.202

### Reviewer

None

**Comment by bilalcim** [comment]
Implemented the functionality for interest selection in edit page.

**Comment by hsuleerkul** [comment]
Image upload will not be implemented for milestone 3 unfortunately
