### ISSUE TITLE
[Mobile] Allowing users to see other user's profiles

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#482]
### Issue

Although a user can see their own profile, they could not view other users' profile pages. The profiles will be accessed via clicking on the user's profile picture.

### Task(s)

- [x] Change current ProfileView to show other user's profile.
- [x] Implement follow and unfollow endpoints in profileService.
- [x] Dynamic Follow / Unfollow buttons

### Deliverable(s)

* Profile picture widget to access user profile.
*  Button for following/unfollowing 

### Acceptance Criteria

* Users should be ableto view other user's profiles. 
* Users should follow or unfollow other users.

### Deadline of the issue

26.12.2022

### Reviewer

None
