### ISSUE TITLE
 Document Individual Reports for Customer Milestone 3

### ISSUE THREAD

**Issue by furkanakkurt1335** [bounswe/bounswe2022group3#491]
### Issue

We need to document our individual reports by Jan 2 for the customer milestone 3. We already have documented our weekly efforts, we just need to synthesize and condense them in this report.

### Task(s)

For each member, document your individual report:
- [x] Arif Akbaba
- [x] Berke Özdemir
- [x] Bilal Aytekin
- [x] Burak Yılmaz
- [x] Furkan Akkurt
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Mehmet Gökberk Arslan
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Nurlan Dadashov
- [x] Salim Kemal Tirit

### Deliverable(s)

* The wiki page of [Final Milestone Individual Reports](https://github.com/bounswe/bounswe2022group3/wiki/451-Final-Milestone---Individual-Reports).

### Acceptance Criteria

* All the members have documented their individual reports.

### Deadline of the issue

02.01.2023 2 PM

### Reviewer

Furkan Akkurt

### Deadline for Review

02.01.2023 8 PM

**Comment by ersoykadir** [comment]
Well Done!
